/* soapDisplayBindingProxy.h
   Generated by gSOAP 2.8.40 for onvifgen/onvif.h

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapDisplayBindingProxy_H
#define soapDisplayBindingProxy_H
#include "soapH.h"

    class SOAP_CMAC DisplayBindingProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        bool soap_own; ///< flag indicating that this context is owned by this proxy when context is shared
        /// Endpoint URL of service 'DisplayBindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in onvifgen/onvif.h, if any
        /// Construct a proxy with new managing context
        DisplayBindingProxy();
        /// Copy constructor
        DisplayBindingProxy(const DisplayBindingProxy& rhs);
        /// Construct proxy given a shared managing context
        DisplayBindingProxy(struct soap*);
        /// Constructor taking an endpoint URL
        DisplayBindingProxy(const char *endpoint);
        /// Constructor taking input and output mode flags for the new managing context
        DisplayBindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        DisplayBindingProxy(const char *endpoint, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        DisplayBindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes non-shared managing context only (use destroy() to delete deserialized data)
        virtual ~DisplayBindingProxy();
        /// Initializer used by constructors
        virtual void DisplayBindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual DisplayBindingProxy *copy() SOAP_PURE_VIRTUAL;
        /// Copy assignment
        DisplayBindingProxy& operator=(const DisplayBindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Add SOAP Header to message
        virtual void soap_header(struct _wsse__Security *wsse__Security);
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault string (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail as string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Web service operation 'GetServiceCapabilities' (returns SOAP_OK or error code)
        virtual int GetServiceCapabilities(_ns7__GetServiceCapabilities *ns7__GetServiceCapabilities, _ns7__GetServiceCapabilitiesResponse &ns7__GetServiceCapabilitiesResponse)
        { return this->GetServiceCapabilities(NULL, NULL, ns7__GetServiceCapabilities, ns7__GetServiceCapabilitiesResponse); }
        virtual int GetServiceCapabilities(const char *soap_endpoint, const char *soap_action, _ns7__GetServiceCapabilities *ns7__GetServiceCapabilities, _ns7__GetServiceCapabilitiesResponse &ns7__GetServiceCapabilitiesResponse);
        /// Web service operation 'GetLayout' (returns SOAP_OK or error code)
        virtual int GetLayout(_ns7__GetLayout *ns7__GetLayout, _ns7__GetLayoutResponse &ns7__GetLayoutResponse)
        { return this->GetLayout(NULL, NULL, ns7__GetLayout, ns7__GetLayoutResponse); }
        virtual int GetLayout(const char *soap_endpoint, const char *soap_action, _ns7__GetLayout *ns7__GetLayout, _ns7__GetLayoutResponse &ns7__GetLayoutResponse);
        /// Web service operation 'SetLayout' (returns SOAP_OK or error code)
        virtual int SetLayout(_ns7__SetLayout *ns7__SetLayout, _ns7__SetLayoutResponse &ns7__SetLayoutResponse)
        { return this->SetLayout(NULL, NULL, ns7__SetLayout, ns7__SetLayoutResponse); }
        virtual int SetLayout(const char *soap_endpoint, const char *soap_action, _ns7__SetLayout *ns7__SetLayout, _ns7__SetLayoutResponse &ns7__SetLayoutResponse);
        /// Web service operation 'GetDisplayOptions' (returns SOAP_OK or error code)
        virtual int GetDisplayOptions(_ns7__GetDisplayOptions *ns7__GetDisplayOptions, _ns7__GetDisplayOptionsResponse &ns7__GetDisplayOptionsResponse)
        { return this->GetDisplayOptions(NULL, NULL, ns7__GetDisplayOptions, ns7__GetDisplayOptionsResponse); }
        virtual int GetDisplayOptions(const char *soap_endpoint, const char *soap_action, _ns7__GetDisplayOptions *ns7__GetDisplayOptions, _ns7__GetDisplayOptionsResponse &ns7__GetDisplayOptionsResponse);
        /// Web service operation 'GetPaneConfigurations' (returns SOAP_OK or error code)
        virtual int GetPaneConfigurations(_ns7__GetPaneConfigurations *ns7__GetPaneConfigurations, _ns7__GetPaneConfigurationsResponse &ns7__GetPaneConfigurationsResponse)
        { return this->GetPaneConfigurations(NULL, NULL, ns7__GetPaneConfigurations, ns7__GetPaneConfigurationsResponse); }
        virtual int GetPaneConfigurations(const char *soap_endpoint, const char *soap_action, _ns7__GetPaneConfigurations *ns7__GetPaneConfigurations, _ns7__GetPaneConfigurationsResponse &ns7__GetPaneConfigurationsResponse);
        /// Web service operation 'GetPaneConfiguration' (returns SOAP_OK or error code)
        virtual int GetPaneConfiguration(_ns7__GetPaneConfiguration *ns7__GetPaneConfiguration, _ns7__GetPaneConfigurationResponse &ns7__GetPaneConfigurationResponse)
        { return this->GetPaneConfiguration(NULL, NULL, ns7__GetPaneConfiguration, ns7__GetPaneConfigurationResponse); }
        virtual int GetPaneConfiguration(const char *soap_endpoint, const char *soap_action, _ns7__GetPaneConfiguration *ns7__GetPaneConfiguration, _ns7__GetPaneConfigurationResponse &ns7__GetPaneConfigurationResponse);
        /// Web service operation 'SetPaneConfigurations' (returns SOAP_OK or error code)
        virtual int SetPaneConfigurations(_ns7__SetPaneConfigurations *ns7__SetPaneConfigurations, _ns7__SetPaneConfigurationsResponse &ns7__SetPaneConfigurationsResponse)
        { return this->SetPaneConfigurations(NULL, NULL, ns7__SetPaneConfigurations, ns7__SetPaneConfigurationsResponse); }
        virtual int SetPaneConfigurations(const char *soap_endpoint, const char *soap_action, _ns7__SetPaneConfigurations *ns7__SetPaneConfigurations, _ns7__SetPaneConfigurationsResponse &ns7__SetPaneConfigurationsResponse);
        /// Web service operation 'SetPaneConfiguration' (returns SOAP_OK or error code)
        virtual int SetPaneConfiguration(_ns7__SetPaneConfiguration *ns7__SetPaneConfiguration, _ns7__SetPaneConfigurationResponse &ns7__SetPaneConfigurationResponse)
        { return this->SetPaneConfiguration(NULL, NULL, ns7__SetPaneConfiguration, ns7__SetPaneConfigurationResponse); }
        virtual int SetPaneConfiguration(const char *soap_endpoint, const char *soap_action, _ns7__SetPaneConfiguration *ns7__SetPaneConfiguration, _ns7__SetPaneConfigurationResponse &ns7__SetPaneConfigurationResponse);
        /// Web service operation 'CreatePaneConfiguration' (returns SOAP_OK or error code)
        virtual int CreatePaneConfiguration(_ns7__CreatePaneConfiguration *ns7__CreatePaneConfiguration, _ns7__CreatePaneConfigurationResponse &ns7__CreatePaneConfigurationResponse)
        { return this->CreatePaneConfiguration(NULL, NULL, ns7__CreatePaneConfiguration, ns7__CreatePaneConfigurationResponse); }
        virtual int CreatePaneConfiguration(const char *soap_endpoint, const char *soap_action, _ns7__CreatePaneConfiguration *ns7__CreatePaneConfiguration, _ns7__CreatePaneConfigurationResponse &ns7__CreatePaneConfigurationResponse);
        /// Web service operation 'DeletePaneConfiguration' (returns SOAP_OK or error code)
        virtual int DeletePaneConfiguration(_ns7__DeletePaneConfiguration *ns7__DeletePaneConfiguration, _ns7__DeletePaneConfigurationResponse &ns7__DeletePaneConfigurationResponse)
        { return this->DeletePaneConfiguration(NULL, NULL, ns7__DeletePaneConfiguration, ns7__DeletePaneConfigurationResponse); }
        virtual int DeletePaneConfiguration(const char *soap_endpoint, const char *soap_action, _ns7__DeletePaneConfiguration *ns7__DeletePaneConfiguration, _ns7__DeletePaneConfigurationResponse &ns7__DeletePaneConfigurationResponse);
    };
#endif
