/* soapMediaBindingProxy.h
   Generated by gSOAP 2.8.40 for onvifgen/onvif.h

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapMediaBindingProxy_H
#define soapMediaBindingProxy_H
#include "soapH.h"

    class SOAP_CMAC MediaBindingProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        bool soap_own; ///< flag indicating that this context is owned by this proxy when context is shared
        /// Endpoint URL of service 'MediaBindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in onvifgen/onvif.h, if any
        /// Construct a proxy with new managing context
        MediaBindingProxy();
        /// Copy constructor
        MediaBindingProxy(const MediaBindingProxy& rhs);
        /// Construct proxy given a shared managing context
        MediaBindingProxy(struct soap*);
        /// Constructor taking an endpoint URL
        MediaBindingProxy(const char *endpoint);
        /// Constructor taking input and output mode flags for the new managing context
        MediaBindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        MediaBindingProxy(const char *endpoint, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        MediaBindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes non-shared managing context only (use destroy() to delete deserialized data)
        virtual ~MediaBindingProxy();
        /// Initializer used by constructors
        virtual void MediaBindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual MediaBindingProxy *copy() SOAP_PURE_VIRTUAL;
        /// Copy assignment
        MediaBindingProxy& operator=(const MediaBindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Add SOAP Header to message
        virtual void soap_header(struct _wsse__Security *wsse__Security);
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault string (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail as string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Web service operation 'GetServiceCapabilities' (returns SOAP_OK or error code)
        virtual int GetServiceCapabilities(_ns9__GetServiceCapabilities *ns9__GetServiceCapabilities, _ns9__GetServiceCapabilitiesResponse &ns9__GetServiceCapabilitiesResponse)
        { return this->GetServiceCapabilities(NULL, NULL, ns9__GetServiceCapabilities, ns9__GetServiceCapabilitiesResponse); }
        virtual int GetServiceCapabilities(const char *soap_endpoint, const char *soap_action, _ns9__GetServiceCapabilities *ns9__GetServiceCapabilities, _ns9__GetServiceCapabilitiesResponse &ns9__GetServiceCapabilitiesResponse);
        /// Web service operation 'GetVideoSources' (returns SOAP_OK or error code)
        virtual int GetVideoSources(_ns9__GetVideoSources *ns9__GetVideoSources, _ns9__GetVideoSourcesResponse &ns9__GetVideoSourcesResponse)
        { return this->GetVideoSources(NULL, NULL, ns9__GetVideoSources, ns9__GetVideoSourcesResponse); }
        virtual int GetVideoSources(const char *soap_endpoint, const char *soap_action, _ns9__GetVideoSources *ns9__GetVideoSources, _ns9__GetVideoSourcesResponse &ns9__GetVideoSourcesResponse);
        /// Web service operation 'GetAudioSources' (returns SOAP_OK or error code)
        virtual int GetAudioSources(_ns9__GetAudioSources *ns9__GetAudioSources, _ns9__GetAudioSourcesResponse &ns9__GetAudioSourcesResponse)
        { return this->GetAudioSources(NULL, NULL, ns9__GetAudioSources, ns9__GetAudioSourcesResponse); }
        virtual int GetAudioSources(const char *soap_endpoint, const char *soap_action, _ns9__GetAudioSources *ns9__GetAudioSources, _ns9__GetAudioSourcesResponse &ns9__GetAudioSourcesResponse);
        /// Web service operation 'GetAudioOutputs' (returns SOAP_OK or error code)
        virtual int GetAudioOutputs(_ns9__GetAudioOutputs *ns9__GetAudioOutputs, _ns9__GetAudioOutputsResponse &ns9__GetAudioOutputsResponse)
        { return this->GetAudioOutputs(NULL, NULL, ns9__GetAudioOutputs, ns9__GetAudioOutputsResponse); }
        virtual int GetAudioOutputs(const char *soap_endpoint, const char *soap_action, _ns9__GetAudioOutputs *ns9__GetAudioOutputs, _ns9__GetAudioOutputsResponse &ns9__GetAudioOutputsResponse);
        /// Web service operation 'CreateProfile' (returns SOAP_OK or error code)
        virtual int CreateProfile(_ns9__CreateProfile *ns9__CreateProfile, _ns9__CreateProfileResponse &ns9__CreateProfileResponse)
        { return this->CreateProfile(NULL, NULL, ns9__CreateProfile, ns9__CreateProfileResponse); }
        virtual int CreateProfile(const char *soap_endpoint, const char *soap_action, _ns9__CreateProfile *ns9__CreateProfile, _ns9__CreateProfileResponse &ns9__CreateProfileResponse);
        /// Web service operation 'GetProfile' (returns SOAP_OK or error code)
        virtual int GetProfile(_ns9__GetProfile *ns9__GetProfile, _ns9__GetProfileResponse &ns9__GetProfileResponse)
        { return this->GetProfile(NULL, NULL, ns9__GetProfile, ns9__GetProfileResponse); }
        virtual int GetProfile(const char *soap_endpoint, const char *soap_action, _ns9__GetProfile *ns9__GetProfile, _ns9__GetProfileResponse &ns9__GetProfileResponse);
        /// Web service operation 'GetProfiles' (returns SOAP_OK or error code)
        virtual int GetProfiles(_ns9__GetProfiles *ns9__GetProfiles, _ns9__GetProfilesResponse &ns9__GetProfilesResponse)
        { return this->GetProfiles(NULL, NULL, ns9__GetProfiles, ns9__GetProfilesResponse); }
        virtual int GetProfiles(const char *soap_endpoint, const char *soap_action, _ns9__GetProfiles *ns9__GetProfiles, _ns9__GetProfilesResponse &ns9__GetProfilesResponse);
        /// Web service operation 'AddVideoEncoderConfiguration' (returns SOAP_OK or error code)
        virtual int AddVideoEncoderConfiguration(_ns9__AddVideoEncoderConfiguration *ns9__AddVideoEncoderConfiguration, _ns9__AddVideoEncoderConfigurationResponse &ns9__AddVideoEncoderConfigurationResponse)
        { return this->AddVideoEncoderConfiguration(NULL, NULL, ns9__AddVideoEncoderConfiguration, ns9__AddVideoEncoderConfigurationResponse); }
        virtual int AddVideoEncoderConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__AddVideoEncoderConfiguration *ns9__AddVideoEncoderConfiguration, _ns9__AddVideoEncoderConfigurationResponse &ns9__AddVideoEncoderConfigurationResponse);
        /// Web service operation 'AddVideoSourceConfiguration' (returns SOAP_OK or error code)
        virtual int AddVideoSourceConfiguration(_ns9__AddVideoSourceConfiguration *ns9__AddVideoSourceConfiguration, _ns9__AddVideoSourceConfigurationResponse &ns9__AddVideoSourceConfigurationResponse)
        { return this->AddVideoSourceConfiguration(NULL, NULL, ns9__AddVideoSourceConfiguration, ns9__AddVideoSourceConfigurationResponse); }
        virtual int AddVideoSourceConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__AddVideoSourceConfiguration *ns9__AddVideoSourceConfiguration, _ns9__AddVideoSourceConfigurationResponse &ns9__AddVideoSourceConfigurationResponse);
        /// Web service operation 'AddAudioEncoderConfiguration' (returns SOAP_OK or error code)
        virtual int AddAudioEncoderConfiguration(_ns9__AddAudioEncoderConfiguration *ns9__AddAudioEncoderConfiguration, _ns9__AddAudioEncoderConfigurationResponse &ns9__AddAudioEncoderConfigurationResponse)
        { return this->AddAudioEncoderConfiguration(NULL, NULL, ns9__AddAudioEncoderConfiguration, ns9__AddAudioEncoderConfigurationResponse); }
        virtual int AddAudioEncoderConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__AddAudioEncoderConfiguration *ns9__AddAudioEncoderConfiguration, _ns9__AddAudioEncoderConfigurationResponse &ns9__AddAudioEncoderConfigurationResponse);
        /// Web service operation 'AddAudioSourceConfiguration' (returns SOAP_OK or error code)
        virtual int AddAudioSourceConfiguration(_ns9__AddAudioSourceConfiguration *ns9__AddAudioSourceConfiguration, _ns9__AddAudioSourceConfigurationResponse &ns9__AddAudioSourceConfigurationResponse)
        { return this->AddAudioSourceConfiguration(NULL, NULL, ns9__AddAudioSourceConfiguration, ns9__AddAudioSourceConfigurationResponse); }
        virtual int AddAudioSourceConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__AddAudioSourceConfiguration *ns9__AddAudioSourceConfiguration, _ns9__AddAudioSourceConfigurationResponse &ns9__AddAudioSourceConfigurationResponse);
        /// Web service operation 'AddPTZConfiguration' (returns SOAP_OK or error code)
        virtual int AddPTZConfiguration(_ns9__AddPTZConfiguration *ns9__AddPTZConfiguration, _ns9__AddPTZConfigurationResponse &ns9__AddPTZConfigurationResponse)
        { return this->AddPTZConfiguration(NULL, NULL, ns9__AddPTZConfiguration, ns9__AddPTZConfigurationResponse); }
        virtual int AddPTZConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__AddPTZConfiguration *ns9__AddPTZConfiguration, _ns9__AddPTZConfigurationResponse &ns9__AddPTZConfigurationResponse);
        /// Web service operation 'AddVideoAnalyticsConfiguration' (returns SOAP_OK or error code)
        virtual int AddVideoAnalyticsConfiguration(_ns9__AddVideoAnalyticsConfiguration *ns9__AddVideoAnalyticsConfiguration, _ns9__AddVideoAnalyticsConfigurationResponse &ns9__AddVideoAnalyticsConfigurationResponse)
        { return this->AddVideoAnalyticsConfiguration(NULL, NULL, ns9__AddVideoAnalyticsConfiguration, ns9__AddVideoAnalyticsConfigurationResponse); }
        virtual int AddVideoAnalyticsConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__AddVideoAnalyticsConfiguration *ns9__AddVideoAnalyticsConfiguration, _ns9__AddVideoAnalyticsConfigurationResponse &ns9__AddVideoAnalyticsConfigurationResponse);
        /// Web service operation 'AddMetadataConfiguration' (returns SOAP_OK or error code)
        virtual int AddMetadataConfiguration(_ns9__AddMetadataConfiguration *ns9__AddMetadataConfiguration, _ns9__AddMetadataConfigurationResponse &ns9__AddMetadataConfigurationResponse)
        { return this->AddMetadataConfiguration(NULL, NULL, ns9__AddMetadataConfiguration, ns9__AddMetadataConfigurationResponse); }
        virtual int AddMetadataConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__AddMetadataConfiguration *ns9__AddMetadataConfiguration, _ns9__AddMetadataConfigurationResponse &ns9__AddMetadataConfigurationResponse);
        /// Web service operation 'AddAudioOutputConfiguration' (returns SOAP_OK or error code)
        virtual int AddAudioOutputConfiguration(_ns9__AddAudioOutputConfiguration *ns9__AddAudioOutputConfiguration, _ns9__AddAudioOutputConfigurationResponse &ns9__AddAudioOutputConfigurationResponse)
        { return this->AddAudioOutputConfiguration(NULL, NULL, ns9__AddAudioOutputConfiguration, ns9__AddAudioOutputConfigurationResponse); }
        virtual int AddAudioOutputConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__AddAudioOutputConfiguration *ns9__AddAudioOutputConfiguration, _ns9__AddAudioOutputConfigurationResponse &ns9__AddAudioOutputConfigurationResponse);
        /// Web service operation 'AddAudioDecoderConfiguration' (returns SOAP_OK or error code)
        virtual int AddAudioDecoderConfiguration(_ns9__AddAudioDecoderConfiguration *ns9__AddAudioDecoderConfiguration, _ns9__AddAudioDecoderConfigurationResponse &ns9__AddAudioDecoderConfigurationResponse)
        { return this->AddAudioDecoderConfiguration(NULL, NULL, ns9__AddAudioDecoderConfiguration, ns9__AddAudioDecoderConfigurationResponse); }
        virtual int AddAudioDecoderConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__AddAudioDecoderConfiguration *ns9__AddAudioDecoderConfiguration, _ns9__AddAudioDecoderConfigurationResponse &ns9__AddAudioDecoderConfigurationResponse);
        /// Web service operation 'RemoveVideoEncoderConfiguration' (returns SOAP_OK or error code)
        virtual int RemoveVideoEncoderConfiguration(_ns9__RemoveVideoEncoderConfiguration *ns9__RemoveVideoEncoderConfiguration, _ns9__RemoveVideoEncoderConfigurationResponse &ns9__RemoveVideoEncoderConfigurationResponse)
        { return this->RemoveVideoEncoderConfiguration(NULL, NULL, ns9__RemoveVideoEncoderConfiguration, ns9__RemoveVideoEncoderConfigurationResponse); }
        virtual int RemoveVideoEncoderConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__RemoveVideoEncoderConfiguration *ns9__RemoveVideoEncoderConfiguration, _ns9__RemoveVideoEncoderConfigurationResponse &ns9__RemoveVideoEncoderConfigurationResponse);
        /// Web service operation 'RemoveVideoSourceConfiguration' (returns SOAP_OK or error code)
        virtual int RemoveVideoSourceConfiguration(_ns9__RemoveVideoSourceConfiguration *ns9__RemoveVideoSourceConfiguration, _ns9__RemoveVideoSourceConfigurationResponse &ns9__RemoveVideoSourceConfigurationResponse)
        { return this->RemoveVideoSourceConfiguration(NULL, NULL, ns9__RemoveVideoSourceConfiguration, ns9__RemoveVideoSourceConfigurationResponse); }
        virtual int RemoveVideoSourceConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__RemoveVideoSourceConfiguration *ns9__RemoveVideoSourceConfiguration, _ns9__RemoveVideoSourceConfigurationResponse &ns9__RemoveVideoSourceConfigurationResponse);
        /// Web service operation 'RemoveAudioEncoderConfiguration' (returns SOAP_OK or error code)
        virtual int RemoveAudioEncoderConfiguration(_ns9__RemoveAudioEncoderConfiguration *ns9__RemoveAudioEncoderConfiguration, _ns9__RemoveAudioEncoderConfigurationResponse &ns9__RemoveAudioEncoderConfigurationResponse)
        { return this->RemoveAudioEncoderConfiguration(NULL, NULL, ns9__RemoveAudioEncoderConfiguration, ns9__RemoveAudioEncoderConfigurationResponse); }
        virtual int RemoveAudioEncoderConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__RemoveAudioEncoderConfiguration *ns9__RemoveAudioEncoderConfiguration, _ns9__RemoveAudioEncoderConfigurationResponse &ns9__RemoveAudioEncoderConfigurationResponse);
        /// Web service operation 'RemoveAudioSourceConfiguration' (returns SOAP_OK or error code)
        virtual int RemoveAudioSourceConfiguration(_ns9__RemoveAudioSourceConfiguration *ns9__RemoveAudioSourceConfiguration, _ns9__RemoveAudioSourceConfigurationResponse &ns9__RemoveAudioSourceConfigurationResponse)
        { return this->RemoveAudioSourceConfiguration(NULL, NULL, ns9__RemoveAudioSourceConfiguration, ns9__RemoveAudioSourceConfigurationResponse); }
        virtual int RemoveAudioSourceConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__RemoveAudioSourceConfiguration *ns9__RemoveAudioSourceConfiguration, _ns9__RemoveAudioSourceConfigurationResponse &ns9__RemoveAudioSourceConfigurationResponse);
        /// Web service operation 'RemovePTZConfiguration' (returns SOAP_OK or error code)
        virtual int RemovePTZConfiguration(_ns9__RemovePTZConfiguration *ns9__RemovePTZConfiguration, _ns9__RemovePTZConfigurationResponse &ns9__RemovePTZConfigurationResponse)
        { return this->RemovePTZConfiguration(NULL, NULL, ns9__RemovePTZConfiguration, ns9__RemovePTZConfigurationResponse); }
        virtual int RemovePTZConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__RemovePTZConfiguration *ns9__RemovePTZConfiguration, _ns9__RemovePTZConfigurationResponse &ns9__RemovePTZConfigurationResponse);
        /// Web service operation 'RemoveVideoAnalyticsConfiguration' (returns SOAP_OK or error code)
        virtual int RemoveVideoAnalyticsConfiguration(_ns9__RemoveVideoAnalyticsConfiguration *ns9__RemoveVideoAnalyticsConfiguration, _ns9__RemoveVideoAnalyticsConfigurationResponse &ns9__RemoveVideoAnalyticsConfigurationResponse)
        { return this->RemoveVideoAnalyticsConfiguration(NULL, NULL, ns9__RemoveVideoAnalyticsConfiguration, ns9__RemoveVideoAnalyticsConfigurationResponse); }
        virtual int RemoveVideoAnalyticsConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__RemoveVideoAnalyticsConfiguration *ns9__RemoveVideoAnalyticsConfiguration, _ns9__RemoveVideoAnalyticsConfigurationResponse &ns9__RemoveVideoAnalyticsConfigurationResponse);
        /// Web service operation 'RemoveMetadataConfiguration' (returns SOAP_OK or error code)
        virtual int RemoveMetadataConfiguration(_ns9__RemoveMetadataConfiguration *ns9__RemoveMetadataConfiguration, _ns9__RemoveMetadataConfigurationResponse &ns9__RemoveMetadataConfigurationResponse)
        { return this->RemoveMetadataConfiguration(NULL, NULL, ns9__RemoveMetadataConfiguration, ns9__RemoveMetadataConfigurationResponse); }
        virtual int RemoveMetadataConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__RemoveMetadataConfiguration *ns9__RemoveMetadataConfiguration, _ns9__RemoveMetadataConfigurationResponse &ns9__RemoveMetadataConfigurationResponse);
        /// Web service operation 'RemoveAudioOutputConfiguration' (returns SOAP_OK or error code)
        virtual int RemoveAudioOutputConfiguration(_ns9__RemoveAudioOutputConfiguration *ns9__RemoveAudioOutputConfiguration, _ns9__RemoveAudioOutputConfigurationResponse &ns9__RemoveAudioOutputConfigurationResponse)
        { return this->RemoveAudioOutputConfiguration(NULL, NULL, ns9__RemoveAudioOutputConfiguration, ns9__RemoveAudioOutputConfigurationResponse); }
        virtual int RemoveAudioOutputConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__RemoveAudioOutputConfiguration *ns9__RemoveAudioOutputConfiguration, _ns9__RemoveAudioOutputConfigurationResponse &ns9__RemoveAudioOutputConfigurationResponse);
        /// Web service operation 'RemoveAudioDecoderConfiguration' (returns SOAP_OK or error code)
        virtual int RemoveAudioDecoderConfiguration(_ns9__RemoveAudioDecoderConfiguration *ns9__RemoveAudioDecoderConfiguration, _ns9__RemoveAudioDecoderConfigurationResponse &ns9__RemoveAudioDecoderConfigurationResponse)
        { return this->RemoveAudioDecoderConfiguration(NULL, NULL, ns9__RemoveAudioDecoderConfiguration, ns9__RemoveAudioDecoderConfigurationResponse); }
        virtual int RemoveAudioDecoderConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__RemoveAudioDecoderConfiguration *ns9__RemoveAudioDecoderConfiguration, _ns9__RemoveAudioDecoderConfigurationResponse &ns9__RemoveAudioDecoderConfigurationResponse);
        /// Web service operation 'DeleteProfile' (returns SOAP_OK or error code)
        virtual int DeleteProfile(_ns9__DeleteProfile *ns9__DeleteProfile, _ns9__DeleteProfileResponse &ns9__DeleteProfileResponse)
        { return this->DeleteProfile(NULL, NULL, ns9__DeleteProfile, ns9__DeleteProfileResponse); }
        virtual int DeleteProfile(const char *soap_endpoint, const char *soap_action, _ns9__DeleteProfile *ns9__DeleteProfile, _ns9__DeleteProfileResponse &ns9__DeleteProfileResponse);
        /// Web service operation 'GetVideoSourceConfigurations' (returns SOAP_OK or error code)
        virtual int GetVideoSourceConfigurations(_ns9__GetVideoSourceConfigurations *ns9__GetVideoSourceConfigurations, _ns9__GetVideoSourceConfigurationsResponse &ns9__GetVideoSourceConfigurationsResponse)
        { return this->GetVideoSourceConfigurations(NULL, NULL, ns9__GetVideoSourceConfigurations, ns9__GetVideoSourceConfigurationsResponse); }
        virtual int GetVideoSourceConfigurations(const char *soap_endpoint, const char *soap_action, _ns9__GetVideoSourceConfigurations *ns9__GetVideoSourceConfigurations, _ns9__GetVideoSourceConfigurationsResponse &ns9__GetVideoSourceConfigurationsResponse);
        /// Web service operation 'GetVideoEncoderConfigurations' (returns SOAP_OK or error code)
        virtual int GetVideoEncoderConfigurations(_ns9__GetVideoEncoderConfigurations *ns9__GetVideoEncoderConfigurations, _ns9__GetVideoEncoderConfigurationsResponse &ns9__GetVideoEncoderConfigurationsResponse)
        { return this->GetVideoEncoderConfigurations(NULL, NULL, ns9__GetVideoEncoderConfigurations, ns9__GetVideoEncoderConfigurationsResponse); }
        virtual int GetVideoEncoderConfigurations(const char *soap_endpoint, const char *soap_action, _ns9__GetVideoEncoderConfigurations *ns9__GetVideoEncoderConfigurations, _ns9__GetVideoEncoderConfigurationsResponse &ns9__GetVideoEncoderConfigurationsResponse);
        /// Web service operation 'GetAudioSourceConfigurations' (returns SOAP_OK or error code)
        virtual int GetAudioSourceConfigurations(_ns9__GetAudioSourceConfigurations *ns9__GetAudioSourceConfigurations, _ns9__GetAudioSourceConfigurationsResponse &ns9__GetAudioSourceConfigurationsResponse)
        { return this->GetAudioSourceConfigurations(NULL, NULL, ns9__GetAudioSourceConfigurations, ns9__GetAudioSourceConfigurationsResponse); }
        virtual int GetAudioSourceConfigurations(const char *soap_endpoint, const char *soap_action, _ns9__GetAudioSourceConfigurations *ns9__GetAudioSourceConfigurations, _ns9__GetAudioSourceConfigurationsResponse &ns9__GetAudioSourceConfigurationsResponse);
        /// Web service operation 'GetAudioEncoderConfigurations' (returns SOAP_OK or error code)
        virtual int GetAudioEncoderConfigurations(_ns9__GetAudioEncoderConfigurations *ns9__GetAudioEncoderConfigurations, _ns9__GetAudioEncoderConfigurationsResponse &ns9__GetAudioEncoderConfigurationsResponse)
        { return this->GetAudioEncoderConfigurations(NULL, NULL, ns9__GetAudioEncoderConfigurations, ns9__GetAudioEncoderConfigurationsResponse); }
        virtual int GetAudioEncoderConfigurations(const char *soap_endpoint, const char *soap_action, _ns9__GetAudioEncoderConfigurations *ns9__GetAudioEncoderConfigurations, _ns9__GetAudioEncoderConfigurationsResponse &ns9__GetAudioEncoderConfigurationsResponse);
        /// Web service operation 'GetVideoAnalyticsConfigurations' (returns SOAP_OK or error code)
        virtual int GetVideoAnalyticsConfigurations(_ns9__GetVideoAnalyticsConfigurations *ns9__GetVideoAnalyticsConfigurations, _ns9__GetVideoAnalyticsConfigurationsResponse &ns9__GetVideoAnalyticsConfigurationsResponse)
        { return this->GetVideoAnalyticsConfigurations(NULL, NULL, ns9__GetVideoAnalyticsConfigurations, ns9__GetVideoAnalyticsConfigurationsResponse); }
        virtual int GetVideoAnalyticsConfigurations(const char *soap_endpoint, const char *soap_action, _ns9__GetVideoAnalyticsConfigurations *ns9__GetVideoAnalyticsConfigurations, _ns9__GetVideoAnalyticsConfigurationsResponse &ns9__GetVideoAnalyticsConfigurationsResponse);
        /// Web service operation 'GetMetadataConfigurations' (returns SOAP_OK or error code)
        virtual int GetMetadataConfigurations(_ns9__GetMetadataConfigurations *ns9__GetMetadataConfigurations, _ns9__GetMetadataConfigurationsResponse &ns9__GetMetadataConfigurationsResponse)
        { return this->GetMetadataConfigurations(NULL, NULL, ns9__GetMetadataConfigurations, ns9__GetMetadataConfigurationsResponse); }
        virtual int GetMetadataConfigurations(const char *soap_endpoint, const char *soap_action, _ns9__GetMetadataConfigurations *ns9__GetMetadataConfigurations, _ns9__GetMetadataConfigurationsResponse &ns9__GetMetadataConfigurationsResponse);
        /// Web service operation 'GetAudioOutputConfigurations' (returns SOAP_OK or error code)
        virtual int GetAudioOutputConfigurations(_ns9__GetAudioOutputConfigurations *ns9__GetAudioOutputConfigurations, _ns9__GetAudioOutputConfigurationsResponse &ns9__GetAudioOutputConfigurationsResponse)
        { return this->GetAudioOutputConfigurations(NULL, NULL, ns9__GetAudioOutputConfigurations, ns9__GetAudioOutputConfigurationsResponse); }
        virtual int GetAudioOutputConfigurations(const char *soap_endpoint, const char *soap_action, _ns9__GetAudioOutputConfigurations *ns9__GetAudioOutputConfigurations, _ns9__GetAudioOutputConfigurationsResponse &ns9__GetAudioOutputConfigurationsResponse);
        /// Web service operation 'GetAudioDecoderConfigurations' (returns SOAP_OK or error code)
        virtual int GetAudioDecoderConfigurations(_ns9__GetAudioDecoderConfigurations *ns9__GetAudioDecoderConfigurations, _ns9__GetAudioDecoderConfigurationsResponse &ns9__GetAudioDecoderConfigurationsResponse)
        { return this->GetAudioDecoderConfigurations(NULL, NULL, ns9__GetAudioDecoderConfigurations, ns9__GetAudioDecoderConfigurationsResponse); }
        virtual int GetAudioDecoderConfigurations(const char *soap_endpoint, const char *soap_action, _ns9__GetAudioDecoderConfigurations *ns9__GetAudioDecoderConfigurations, _ns9__GetAudioDecoderConfigurationsResponse &ns9__GetAudioDecoderConfigurationsResponse);
        /// Web service operation 'GetVideoSourceConfiguration' (returns SOAP_OK or error code)
        virtual int GetVideoSourceConfiguration(_ns9__GetVideoSourceConfiguration *ns9__GetVideoSourceConfiguration, _ns9__GetVideoSourceConfigurationResponse &ns9__GetVideoSourceConfigurationResponse)
        { return this->GetVideoSourceConfiguration(NULL, NULL, ns9__GetVideoSourceConfiguration, ns9__GetVideoSourceConfigurationResponse); }
        virtual int GetVideoSourceConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__GetVideoSourceConfiguration *ns9__GetVideoSourceConfiguration, _ns9__GetVideoSourceConfigurationResponse &ns9__GetVideoSourceConfigurationResponse);
        /// Web service operation 'GetVideoEncoderConfiguration' (returns SOAP_OK or error code)
        virtual int GetVideoEncoderConfiguration(_ns9__GetVideoEncoderConfiguration *ns9__GetVideoEncoderConfiguration, _ns9__GetVideoEncoderConfigurationResponse &ns9__GetVideoEncoderConfigurationResponse)
        { return this->GetVideoEncoderConfiguration(NULL, NULL, ns9__GetVideoEncoderConfiguration, ns9__GetVideoEncoderConfigurationResponse); }
        virtual int GetVideoEncoderConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__GetVideoEncoderConfiguration *ns9__GetVideoEncoderConfiguration, _ns9__GetVideoEncoderConfigurationResponse &ns9__GetVideoEncoderConfigurationResponse);
        /// Web service operation 'GetAudioSourceConfiguration' (returns SOAP_OK or error code)
        virtual int GetAudioSourceConfiguration(_ns9__GetAudioSourceConfiguration *ns9__GetAudioSourceConfiguration, _ns9__GetAudioSourceConfigurationResponse &ns9__GetAudioSourceConfigurationResponse)
        { return this->GetAudioSourceConfiguration(NULL, NULL, ns9__GetAudioSourceConfiguration, ns9__GetAudioSourceConfigurationResponse); }
        virtual int GetAudioSourceConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__GetAudioSourceConfiguration *ns9__GetAudioSourceConfiguration, _ns9__GetAudioSourceConfigurationResponse &ns9__GetAudioSourceConfigurationResponse);
        /// Web service operation 'GetAudioEncoderConfiguration' (returns SOAP_OK or error code)
        virtual int GetAudioEncoderConfiguration(_ns9__GetAudioEncoderConfiguration *ns9__GetAudioEncoderConfiguration, _ns9__GetAudioEncoderConfigurationResponse &ns9__GetAudioEncoderConfigurationResponse)
        { return this->GetAudioEncoderConfiguration(NULL, NULL, ns9__GetAudioEncoderConfiguration, ns9__GetAudioEncoderConfigurationResponse); }
        virtual int GetAudioEncoderConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__GetAudioEncoderConfiguration *ns9__GetAudioEncoderConfiguration, _ns9__GetAudioEncoderConfigurationResponse &ns9__GetAudioEncoderConfigurationResponse);
        /// Web service operation 'GetVideoAnalyticsConfiguration' (returns SOAP_OK or error code)
        virtual int GetVideoAnalyticsConfiguration(_ns9__GetVideoAnalyticsConfiguration *ns9__GetVideoAnalyticsConfiguration, _ns9__GetVideoAnalyticsConfigurationResponse &ns9__GetVideoAnalyticsConfigurationResponse)
        { return this->GetVideoAnalyticsConfiguration(NULL, NULL, ns9__GetVideoAnalyticsConfiguration, ns9__GetVideoAnalyticsConfigurationResponse); }
        virtual int GetVideoAnalyticsConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__GetVideoAnalyticsConfiguration *ns9__GetVideoAnalyticsConfiguration, _ns9__GetVideoAnalyticsConfigurationResponse &ns9__GetVideoAnalyticsConfigurationResponse);
        /// Web service operation 'GetMetadataConfiguration' (returns SOAP_OK or error code)
        virtual int GetMetadataConfiguration(_ns9__GetMetadataConfiguration *ns9__GetMetadataConfiguration, _ns9__GetMetadataConfigurationResponse &ns9__GetMetadataConfigurationResponse)
        { return this->GetMetadataConfiguration(NULL, NULL, ns9__GetMetadataConfiguration, ns9__GetMetadataConfigurationResponse); }
        virtual int GetMetadataConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__GetMetadataConfiguration *ns9__GetMetadataConfiguration, _ns9__GetMetadataConfigurationResponse &ns9__GetMetadataConfigurationResponse);
        /// Web service operation 'GetAudioOutputConfiguration' (returns SOAP_OK or error code)
        virtual int GetAudioOutputConfiguration(_ns9__GetAudioOutputConfiguration *ns9__GetAudioOutputConfiguration, _ns9__GetAudioOutputConfigurationResponse &ns9__GetAudioOutputConfigurationResponse)
        { return this->GetAudioOutputConfiguration(NULL, NULL, ns9__GetAudioOutputConfiguration, ns9__GetAudioOutputConfigurationResponse); }
        virtual int GetAudioOutputConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__GetAudioOutputConfiguration *ns9__GetAudioOutputConfiguration, _ns9__GetAudioOutputConfigurationResponse &ns9__GetAudioOutputConfigurationResponse);
        /// Web service operation 'GetAudioDecoderConfiguration' (returns SOAP_OK or error code)
        virtual int GetAudioDecoderConfiguration(_ns9__GetAudioDecoderConfiguration *ns9__GetAudioDecoderConfiguration, _ns9__GetAudioDecoderConfigurationResponse &ns9__GetAudioDecoderConfigurationResponse)
        { return this->GetAudioDecoderConfiguration(NULL, NULL, ns9__GetAudioDecoderConfiguration, ns9__GetAudioDecoderConfigurationResponse); }
        virtual int GetAudioDecoderConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__GetAudioDecoderConfiguration *ns9__GetAudioDecoderConfiguration, _ns9__GetAudioDecoderConfigurationResponse &ns9__GetAudioDecoderConfigurationResponse);
        /// Web service operation 'GetCompatibleVideoEncoderConfigurations' (returns SOAP_OK or error code)
        virtual int GetCompatibleVideoEncoderConfigurations(_ns9__GetCompatibleVideoEncoderConfigurations *ns9__GetCompatibleVideoEncoderConfigurations, _ns9__GetCompatibleVideoEncoderConfigurationsResponse &ns9__GetCompatibleVideoEncoderConfigurationsResponse)
        { return this->GetCompatibleVideoEncoderConfigurations(NULL, NULL, ns9__GetCompatibleVideoEncoderConfigurations, ns9__GetCompatibleVideoEncoderConfigurationsResponse); }
        virtual int GetCompatibleVideoEncoderConfigurations(const char *soap_endpoint, const char *soap_action, _ns9__GetCompatibleVideoEncoderConfigurations *ns9__GetCompatibleVideoEncoderConfigurations, _ns9__GetCompatibleVideoEncoderConfigurationsResponse &ns9__GetCompatibleVideoEncoderConfigurationsResponse);
        /// Web service operation 'GetCompatibleVideoSourceConfigurations' (returns SOAP_OK or error code)
        virtual int GetCompatibleVideoSourceConfigurations(_ns9__GetCompatibleVideoSourceConfigurations *ns9__GetCompatibleVideoSourceConfigurations, _ns9__GetCompatibleVideoSourceConfigurationsResponse &ns9__GetCompatibleVideoSourceConfigurationsResponse)
        { return this->GetCompatibleVideoSourceConfigurations(NULL, NULL, ns9__GetCompatibleVideoSourceConfigurations, ns9__GetCompatibleVideoSourceConfigurationsResponse); }
        virtual int GetCompatibleVideoSourceConfigurations(const char *soap_endpoint, const char *soap_action, _ns9__GetCompatibleVideoSourceConfigurations *ns9__GetCompatibleVideoSourceConfigurations, _ns9__GetCompatibleVideoSourceConfigurationsResponse &ns9__GetCompatibleVideoSourceConfigurationsResponse);
        /// Web service operation 'GetCompatibleAudioEncoderConfigurations' (returns SOAP_OK or error code)
        virtual int GetCompatibleAudioEncoderConfigurations(_ns9__GetCompatibleAudioEncoderConfigurations *ns9__GetCompatibleAudioEncoderConfigurations, _ns9__GetCompatibleAudioEncoderConfigurationsResponse &ns9__GetCompatibleAudioEncoderConfigurationsResponse)
        { return this->GetCompatibleAudioEncoderConfigurations(NULL, NULL, ns9__GetCompatibleAudioEncoderConfigurations, ns9__GetCompatibleAudioEncoderConfigurationsResponse); }
        virtual int GetCompatibleAudioEncoderConfigurations(const char *soap_endpoint, const char *soap_action, _ns9__GetCompatibleAudioEncoderConfigurations *ns9__GetCompatibleAudioEncoderConfigurations, _ns9__GetCompatibleAudioEncoderConfigurationsResponse &ns9__GetCompatibleAudioEncoderConfigurationsResponse);
        /// Web service operation 'GetCompatibleAudioSourceConfigurations' (returns SOAP_OK or error code)
        virtual int GetCompatibleAudioSourceConfigurations(_ns9__GetCompatibleAudioSourceConfigurations *ns9__GetCompatibleAudioSourceConfigurations, _ns9__GetCompatibleAudioSourceConfigurationsResponse &ns9__GetCompatibleAudioSourceConfigurationsResponse)
        { return this->GetCompatibleAudioSourceConfigurations(NULL, NULL, ns9__GetCompatibleAudioSourceConfigurations, ns9__GetCompatibleAudioSourceConfigurationsResponse); }
        virtual int GetCompatibleAudioSourceConfigurations(const char *soap_endpoint, const char *soap_action, _ns9__GetCompatibleAudioSourceConfigurations *ns9__GetCompatibleAudioSourceConfigurations, _ns9__GetCompatibleAudioSourceConfigurationsResponse &ns9__GetCompatibleAudioSourceConfigurationsResponse);
        /// Web service operation 'GetCompatibleVideoAnalyticsConfigurations' (returns SOAP_OK or error code)
        virtual int GetCompatibleVideoAnalyticsConfigurations(_ns9__GetCompatibleVideoAnalyticsConfigurations *ns9__GetCompatibleVideoAnalyticsConfigurations, _ns9__GetCompatibleVideoAnalyticsConfigurationsResponse &ns9__GetCompatibleVideoAnalyticsConfigurationsResponse)
        { return this->GetCompatibleVideoAnalyticsConfigurations(NULL, NULL, ns9__GetCompatibleVideoAnalyticsConfigurations, ns9__GetCompatibleVideoAnalyticsConfigurationsResponse); }
        virtual int GetCompatibleVideoAnalyticsConfigurations(const char *soap_endpoint, const char *soap_action, _ns9__GetCompatibleVideoAnalyticsConfigurations *ns9__GetCompatibleVideoAnalyticsConfigurations, _ns9__GetCompatibleVideoAnalyticsConfigurationsResponse &ns9__GetCompatibleVideoAnalyticsConfigurationsResponse);
        /// Web service operation 'GetCompatibleMetadataConfigurations' (returns SOAP_OK or error code)
        virtual int GetCompatibleMetadataConfigurations(_ns9__GetCompatibleMetadataConfigurations *ns9__GetCompatibleMetadataConfigurations, _ns9__GetCompatibleMetadataConfigurationsResponse &ns9__GetCompatibleMetadataConfigurationsResponse)
        { return this->GetCompatibleMetadataConfigurations(NULL, NULL, ns9__GetCompatibleMetadataConfigurations, ns9__GetCompatibleMetadataConfigurationsResponse); }
        virtual int GetCompatibleMetadataConfigurations(const char *soap_endpoint, const char *soap_action, _ns9__GetCompatibleMetadataConfigurations *ns9__GetCompatibleMetadataConfigurations, _ns9__GetCompatibleMetadataConfigurationsResponse &ns9__GetCompatibleMetadataConfigurationsResponse);
        /// Web service operation 'GetCompatibleAudioOutputConfigurations' (returns SOAP_OK or error code)
        virtual int GetCompatibleAudioOutputConfigurations(_ns9__GetCompatibleAudioOutputConfigurations *ns9__GetCompatibleAudioOutputConfigurations, _ns9__GetCompatibleAudioOutputConfigurationsResponse &ns9__GetCompatibleAudioOutputConfigurationsResponse)
        { return this->GetCompatibleAudioOutputConfigurations(NULL, NULL, ns9__GetCompatibleAudioOutputConfigurations, ns9__GetCompatibleAudioOutputConfigurationsResponse); }
        virtual int GetCompatibleAudioOutputConfigurations(const char *soap_endpoint, const char *soap_action, _ns9__GetCompatibleAudioOutputConfigurations *ns9__GetCompatibleAudioOutputConfigurations, _ns9__GetCompatibleAudioOutputConfigurationsResponse &ns9__GetCompatibleAudioOutputConfigurationsResponse);
        /// Web service operation 'GetCompatibleAudioDecoderConfigurations' (returns SOAP_OK or error code)
        virtual int GetCompatibleAudioDecoderConfigurations(_ns9__GetCompatibleAudioDecoderConfigurations *ns9__GetCompatibleAudioDecoderConfigurations, _ns9__GetCompatibleAudioDecoderConfigurationsResponse &ns9__GetCompatibleAudioDecoderConfigurationsResponse)
        { return this->GetCompatibleAudioDecoderConfigurations(NULL, NULL, ns9__GetCompatibleAudioDecoderConfigurations, ns9__GetCompatibleAudioDecoderConfigurationsResponse); }
        virtual int GetCompatibleAudioDecoderConfigurations(const char *soap_endpoint, const char *soap_action, _ns9__GetCompatibleAudioDecoderConfigurations *ns9__GetCompatibleAudioDecoderConfigurations, _ns9__GetCompatibleAudioDecoderConfigurationsResponse &ns9__GetCompatibleAudioDecoderConfigurationsResponse);
        /// Web service operation 'SetVideoSourceConfiguration' (returns SOAP_OK or error code)
        virtual int SetVideoSourceConfiguration(_ns9__SetVideoSourceConfiguration *ns9__SetVideoSourceConfiguration, _ns9__SetVideoSourceConfigurationResponse &ns9__SetVideoSourceConfigurationResponse)
        { return this->SetVideoSourceConfiguration(NULL, NULL, ns9__SetVideoSourceConfiguration, ns9__SetVideoSourceConfigurationResponse); }
        virtual int SetVideoSourceConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__SetVideoSourceConfiguration *ns9__SetVideoSourceConfiguration, _ns9__SetVideoSourceConfigurationResponse &ns9__SetVideoSourceConfigurationResponse);
        /// Web service operation 'SetVideoEncoderConfiguration' (returns SOAP_OK or error code)
        virtual int SetVideoEncoderConfiguration(_ns9__SetVideoEncoderConfiguration *ns9__SetVideoEncoderConfiguration, _ns9__SetVideoEncoderConfigurationResponse &ns9__SetVideoEncoderConfigurationResponse)
        { return this->SetVideoEncoderConfiguration(NULL, NULL, ns9__SetVideoEncoderConfiguration, ns9__SetVideoEncoderConfigurationResponse); }
        virtual int SetVideoEncoderConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__SetVideoEncoderConfiguration *ns9__SetVideoEncoderConfiguration, _ns9__SetVideoEncoderConfigurationResponse &ns9__SetVideoEncoderConfigurationResponse);
        /// Web service operation 'SetAudioSourceConfiguration' (returns SOAP_OK or error code)
        virtual int SetAudioSourceConfiguration(_ns9__SetAudioSourceConfiguration *ns9__SetAudioSourceConfiguration, _ns9__SetAudioSourceConfigurationResponse &ns9__SetAudioSourceConfigurationResponse)
        { return this->SetAudioSourceConfiguration(NULL, NULL, ns9__SetAudioSourceConfiguration, ns9__SetAudioSourceConfigurationResponse); }
        virtual int SetAudioSourceConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__SetAudioSourceConfiguration *ns9__SetAudioSourceConfiguration, _ns9__SetAudioSourceConfigurationResponse &ns9__SetAudioSourceConfigurationResponse);
        /// Web service operation 'SetAudioEncoderConfiguration' (returns SOAP_OK or error code)
        virtual int SetAudioEncoderConfiguration(_ns9__SetAudioEncoderConfiguration *ns9__SetAudioEncoderConfiguration, _ns9__SetAudioEncoderConfigurationResponse &ns9__SetAudioEncoderConfigurationResponse)
        { return this->SetAudioEncoderConfiguration(NULL, NULL, ns9__SetAudioEncoderConfiguration, ns9__SetAudioEncoderConfigurationResponse); }
        virtual int SetAudioEncoderConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__SetAudioEncoderConfiguration *ns9__SetAudioEncoderConfiguration, _ns9__SetAudioEncoderConfigurationResponse &ns9__SetAudioEncoderConfigurationResponse);
        /// Web service operation 'SetVideoAnalyticsConfiguration' (returns SOAP_OK or error code)
        virtual int SetVideoAnalyticsConfiguration(_ns9__SetVideoAnalyticsConfiguration *ns9__SetVideoAnalyticsConfiguration, _ns9__SetVideoAnalyticsConfigurationResponse &ns9__SetVideoAnalyticsConfigurationResponse)
        { return this->SetVideoAnalyticsConfiguration(NULL, NULL, ns9__SetVideoAnalyticsConfiguration, ns9__SetVideoAnalyticsConfigurationResponse); }
        virtual int SetVideoAnalyticsConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__SetVideoAnalyticsConfiguration *ns9__SetVideoAnalyticsConfiguration, _ns9__SetVideoAnalyticsConfigurationResponse &ns9__SetVideoAnalyticsConfigurationResponse);
        /// Web service operation 'SetMetadataConfiguration' (returns SOAP_OK or error code)
        virtual int SetMetadataConfiguration(_ns9__SetMetadataConfiguration *ns9__SetMetadataConfiguration, _ns9__SetMetadataConfigurationResponse &ns9__SetMetadataConfigurationResponse)
        { return this->SetMetadataConfiguration(NULL, NULL, ns9__SetMetadataConfiguration, ns9__SetMetadataConfigurationResponse); }
        virtual int SetMetadataConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__SetMetadataConfiguration *ns9__SetMetadataConfiguration, _ns9__SetMetadataConfigurationResponse &ns9__SetMetadataConfigurationResponse);
        /// Web service operation 'SetAudioOutputConfiguration' (returns SOAP_OK or error code)
        virtual int SetAudioOutputConfiguration(_ns9__SetAudioOutputConfiguration *ns9__SetAudioOutputConfiguration, _ns9__SetAudioOutputConfigurationResponse &ns9__SetAudioOutputConfigurationResponse)
        { return this->SetAudioOutputConfiguration(NULL, NULL, ns9__SetAudioOutputConfiguration, ns9__SetAudioOutputConfigurationResponse); }
        virtual int SetAudioOutputConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__SetAudioOutputConfiguration *ns9__SetAudioOutputConfiguration, _ns9__SetAudioOutputConfigurationResponse &ns9__SetAudioOutputConfigurationResponse);
        /// Web service operation 'SetAudioDecoderConfiguration' (returns SOAP_OK or error code)
        virtual int SetAudioDecoderConfiguration(_ns9__SetAudioDecoderConfiguration *ns9__SetAudioDecoderConfiguration, _ns9__SetAudioDecoderConfigurationResponse &ns9__SetAudioDecoderConfigurationResponse)
        { return this->SetAudioDecoderConfiguration(NULL, NULL, ns9__SetAudioDecoderConfiguration, ns9__SetAudioDecoderConfigurationResponse); }
        virtual int SetAudioDecoderConfiguration(const char *soap_endpoint, const char *soap_action, _ns9__SetAudioDecoderConfiguration *ns9__SetAudioDecoderConfiguration, _ns9__SetAudioDecoderConfigurationResponse &ns9__SetAudioDecoderConfigurationResponse);
        /// Web service operation 'GetVideoSourceConfigurationOptions' (returns SOAP_OK or error code)
        virtual int GetVideoSourceConfigurationOptions(_ns9__GetVideoSourceConfigurationOptions *ns9__GetVideoSourceConfigurationOptions, _ns9__GetVideoSourceConfigurationOptionsResponse &ns9__GetVideoSourceConfigurationOptionsResponse)
        { return this->GetVideoSourceConfigurationOptions(NULL, NULL, ns9__GetVideoSourceConfigurationOptions, ns9__GetVideoSourceConfigurationOptionsResponse); }
        virtual int GetVideoSourceConfigurationOptions(const char *soap_endpoint, const char *soap_action, _ns9__GetVideoSourceConfigurationOptions *ns9__GetVideoSourceConfigurationOptions, _ns9__GetVideoSourceConfigurationOptionsResponse &ns9__GetVideoSourceConfigurationOptionsResponse);
        /// Web service operation 'GetVideoEncoderConfigurationOptions' (returns SOAP_OK or error code)
        virtual int GetVideoEncoderConfigurationOptions(_ns9__GetVideoEncoderConfigurationOptions *ns9__GetVideoEncoderConfigurationOptions, _ns9__GetVideoEncoderConfigurationOptionsResponse &ns9__GetVideoEncoderConfigurationOptionsResponse)
        { return this->GetVideoEncoderConfigurationOptions(NULL, NULL, ns9__GetVideoEncoderConfigurationOptions, ns9__GetVideoEncoderConfigurationOptionsResponse); }
        virtual int GetVideoEncoderConfigurationOptions(const char *soap_endpoint, const char *soap_action, _ns9__GetVideoEncoderConfigurationOptions *ns9__GetVideoEncoderConfigurationOptions, _ns9__GetVideoEncoderConfigurationOptionsResponse &ns9__GetVideoEncoderConfigurationOptionsResponse);
        /// Web service operation 'GetAudioSourceConfigurationOptions' (returns SOAP_OK or error code)
        virtual int GetAudioSourceConfigurationOptions(_ns9__GetAudioSourceConfigurationOptions *ns9__GetAudioSourceConfigurationOptions, _ns9__GetAudioSourceConfigurationOptionsResponse &ns9__GetAudioSourceConfigurationOptionsResponse)
        { return this->GetAudioSourceConfigurationOptions(NULL, NULL, ns9__GetAudioSourceConfigurationOptions, ns9__GetAudioSourceConfigurationOptionsResponse); }
        virtual int GetAudioSourceConfigurationOptions(const char *soap_endpoint, const char *soap_action, _ns9__GetAudioSourceConfigurationOptions *ns9__GetAudioSourceConfigurationOptions, _ns9__GetAudioSourceConfigurationOptionsResponse &ns9__GetAudioSourceConfigurationOptionsResponse);
        /// Web service operation 'GetAudioEncoderConfigurationOptions' (returns SOAP_OK or error code)
        virtual int GetAudioEncoderConfigurationOptions(_ns9__GetAudioEncoderConfigurationOptions *ns9__GetAudioEncoderConfigurationOptions, _ns9__GetAudioEncoderConfigurationOptionsResponse &ns9__GetAudioEncoderConfigurationOptionsResponse)
        { return this->GetAudioEncoderConfigurationOptions(NULL, NULL, ns9__GetAudioEncoderConfigurationOptions, ns9__GetAudioEncoderConfigurationOptionsResponse); }
        virtual int GetAudioEncoderConfigurationOptions(const char *soap_endpoint, const char *soap_action, _ns9__GetAudioEncoderConfigurationOptions *ns9__GetAudioEncoderConfigurationOptions, _ns9__GetAudioEncoderConfigurationOptionsResponse &ns9__GetAudioEncoderConfigurationOptionsResponse);
        /// Web service operation 'GetMetadataConfigurationOptions' (returns SOAP_OK or error code)
        virtual int GetMetadataConfigurationOptions(_ns9__GetMetadataConfigurationOptions *ns9__GetMetadataConfigurationOptions, _ns9__GetMetadataConfigurationOptionsResponse &ns9__GetMetadataConfigurationOptionsResponse)
        { return this->GetMetadataConfigurationOptions(NULL, NULL, ns9__GetMetadataConfigurationOptions, ns9__GetMetadataConfigurationOptionsResponse); }
        virtual int GetMetadataConfigurationOptions(const char *soap_endpoint, const char *soap_action, _ns9__GetMetadataConfigurationOptions *ns9__GetMetadataConfigurationOptions, _ns9__GetMetadataConfigurationOptionsResponse &ns9__GetMetadataConfigurationOptionsResponse);
        /// Web service operation 'GetAudioOutputConfigurationOptions' (returns SOAP_OK or error code)
        virtual int GetAudioOutputConfigurationOptions(_ns9__GetAudioOutputConfigurationOptions *ns9__GetAudioOutputConfigurationOptions, _ns9__GetAudioOutputConfigurationOptionsResponse &ns9__GetAudioOutputConfigurationOptionsResponse)
        { return this->GetAudioOutputConfigurationOptions(NULL, NULL, ns9__GetAudioOutputConfigurationOptions, ns9__GetAudioOutputConfigurationOptionsResponse); }
        virtual int GetAudioOutputConfigurationOptions(const char *soap_endpoint, const char *soap_action, _ns9__GetAudioOutputConfigurationOptions *ns9__GetAudioOutputConfigurationOptions, _ns9__GetAudioOutputConfigurationOptionsResponse &ns9__GetAudioOutputConfigurationOptionsResponse);
        /// Web service operation 'GetAudioDecoderConfigurationOptions' (returns SOAP_OK or error code)
        virtual int GetAudioDecoderConfigurationOptions(_ns9__GetAudioDecoderConfigurationOptions *ns9__GetAudioDecoderConfigurationOptions, _ns9__GetAudioDecoderConfigurationOptionsResponse &ns9__GetAudioDecoderConfigurationOptionsResponse)
        { return this->GetAudioDecoderConfigurationOptions(NULL, NULL, ns9__GetAudioDecoderConfigurationOptions, ns9__GetAudioDecoderConfigurationOptionsResponse); }
        virtual int GetAudioDecoderConfigurationOptions(const char *soap_endpoint, const char *soap_action, _ns9__GetAudioDecoderConfigurationOptions *ns9__GetAudioDecoderConfigurationOptions, _ns9__GetAudioDecoderConfigurationOptionsResponse &ns9__GetAudioDecoderConfigurationOptionsResponse);
        /// Web service operation 'GetGuaranteedNumberOfVideoEncoderInstances' (returns SOAP_OK or error code)
        virtual int GetGuaranteedNumberOfVideoEncoderInstances(_ns9__GetGuaranteedNumberOfVideoEncoderInstances *ns9__GetGuaranteedNumberOfVideoEncoderInstances, _ns9__GetGuaranteedNumberOfVideoEncoderInstancesResponse &ns9__GetGuaranteedNumberOfVideoEncoderInstancesResponse)
        { return this->GetGuaranteedNumberOfVideoEncoderInstances(NULL, NULL, ns9__GetGuaranteedNumberOfVideoEncoderInstances, ns9__GetGuaranteedNumberOfVideoEncoderInstancesResponse); }
        virtual int GetGuaranteedNumberOfVideoEncoderInstances(const char *soap_endpoint, const char *soap_action, _ns9__GetGuaranteedNumberOfVideoEncoderInstances *ns9__GetGuaranteedNumberOfVideoEncoderInstances, _ns9__GetGuaranteedNumberOfVideoEncoderInstancesResponse &ns9__GetGuaranteedNumberOfVideoEncoderInstancesResponse);
        /// Web service operation 'GetStreamUri' (returns SOAP_OK or error code)
        virtual int GetStreamUri(_ns9__GetStreamUri *ns9__GetStreamUri, _ns9__GetStreamUriResponse &ns9__GetStreamUriResponse)
        { return this->GetStreamUri(NULL, NULL, ns9__GetStreamUri, ns9__GetStreamUriResponse); }
        virtual int GetStreamUri(const char *soap_endpoint, const char *soap_action, _ns9__GetStreamUri *ns9__GetStreamUri, _ns9__GetStreamUriResponse &ns9__GetStreamUriResponse);
        /// Web service operation 'StartMulticastStreaming' (returns SOAP_OK or error code)
        virtual int StartMulticastStreaming(_ns9__StartMulticastStreaming *ns9__StartMulticastStreaming, _ns9__StartMulticastStreamingResponse &ns9__StartMulticastStreamingResponse)
        { return this->StartMulticastStreaming(NULL, NULL, ns9__StartMulticastStreaming, ns9__StartMulticastStreamingResponse); }
        virtual int StartMulticastStreaming(const char *soap_endpoint, const char *soap_action, _ns9__StartMulticastStreaming *ns9__StartMulticastStreaming, _ns9__StartMulticastStreamingResponse &ns9__StartMulticastStreamingResponse);
        /// Web service operation 'StopMulticastStreaming' (returns SOAP_OK or error code)
        virtual int StopMulticastStreaming(_ns9__StopMulticastStreaming *ns9__StopMulticastStreaming, _ns9__StopMulticastStreamingResponse &ns9__StopMulticastStreamingResponse)
        { return this->StopMulticastStreaming(NULL, NULL, ns9__StopMulticastStreaming, ns9__StopMulticastStreamingResponse); }
        virtual int StopMulticastStreaming(const char *soap_endpoint, const char *soap_action, _ns9__StopMulticastStreaming *ns9__StopMulticastStreaming, _ns9__StopMulticastStreamingResponse &ns9__StopMulticastStreamingResponse);
        /// Web service operation 'SetSynchronizationPoint' (returns SOAP_OK or error code)
        virtual int SetSynchronizationPoint(_ns9__SetSynchronizationPoint *ns9__SetSynchronizationPoint, _ns9__SetSynchronizationPointResponse &ns9__SetSynchronizationPointResponse)
        { return this->SetSynchronizationPoint(NULL, NULL, ns9__SetSynchronizationPoint, ns9__SetSynchronizationPointResponse); }
        virtual int SetSynchronizationPoint(const char *soap_endpoint, const char *soap_action, _ns9__SetSynchronizationPoint *ns9__SetSynchronizationPoint, _ns9__SetSynchronizationPointResponse &ns9__SetSynchronizationPointResponse);
        /// Web service operation 'GetSnapshotUri' (returns SOAP_OK or error code)
        virtual int GetSnapshotUri(_ns9__GetSnapshotUri *ns9__GetSnapshotUri, _ns9__GetSnapshotUriResponse &ns9__GetSnapshotUriResponse)
        { return this->GetSnapshotUri(NULL, NULL, ns9__GetSnapshotUri, ns9__GetSnapshotUriResponse); }
        virtual int GetSnapshotUri(const char *soap_endpoint, const char *soap_action, _ns9__GetSnapshotUri *ns9__GetSnapshotUri, _ns9__GetSnapshotUriResponse &ns9__GetSnapshotUriResponse);
        /// Web service operation 'GetVideoSourceModes' (returns SOAP_OK or error code)
        virtual int GetVideoSourceModes(_ns9__GetVideoSourceModes *ns9__GetVideoSourceModes, _ns9__GetVideoSourceModesResponse &ns9__GetVideoSourceModesResponse)
        { return this->GetVideoSourceModes(NULL, NULL, ns9__GetVideoSourceModes, ns9__GetVideoSourceModesResponse); }
        virtual int GetVideoSourceModes(const char *soap_endpoint, const char *soap_action, _ns9__GetVideoSourceModes *ns9__GetVideoSourceModes, _ns9__GetVideoSourceModesResponse &ns9__GetVideoSourceModesResponse);
        /// Web service operation 'SetVideoSourceMode' (returns SOAP_OK or error code)
        virtual int SetVideoSourceMode(_ns9__SetVideoSourceMode *ns9__SetVideoSourceMode, _ns9__SetVideoSourceModeResponse &ns9__SetVideoSourceModeResponse)
        { return this->SetVideoSourceMode(NULL, NULL, ns9__SetVideoSourceMode, ns9__SetVideoSourceModeResponse); }
        virtual int SetVideoSourceMode(const char *soap_endpoint, const char *soap_action, _ns9__SetVideoSourceMode *ns9__SetVideoSourceMode, _ns9__SetVideoSourceModeResponse &ns9__SetVideoSourceModeResponse);
        /// Web service operation 'GetOSDs' (returns SOAP_OK or error code)
        virtual int GetOSDs(_ns9__GetOSDs *ns9__GetOSDs, _ns9__GetOSDsResponse &ns9__GetOSDsResponse)
        { return this->GetOSDs(NULL, NULL, ns9__GetOSDs, ns9__GetOSDsResponse); }
        virtual int GetOSDs(const char *soap_endpoint, const char *soap_action, _ns9__GetOSDs *ns9__GetOSDs, _ns9__GetOSDsResponse &ns9__GetOSDsResponse);
        /// Web service operation 'GetOSD' (returns SOAP_OK or error code)
        virtual int GetOSD(_ns9__GetOSD *ns9__GetOSD, _ns9__GetOSDResponse &ns9__GetOSDResponse)
        { return this->GetOSD(NULL, NULL, ns9__GetOSD, ns9__GetOSDResponse); }
        virtual int GetOSD(const char *soap_endpoint, const char *soap_action, _ns9__GetOSD *ns9__GetOSD, _ns9__GetOSDResponse &ns9__GetOSDResponse);
        /// Web service operation 'GetOSDOptions' (returns SOAP_OK or error code)
        virtual int GetOSDOptions(_ns9__GetOSDOptions *ns9__GetOSDOptions, _ns9__GetOSDOptionsResponse &ns9__GetOSDOptionsResponse)
        { return this->GetOSDOptions(NULL, NULL, ns9__GetOSDOptions, ns9__GetOSDOptionsResponse); }
        virtual int GetOSDOptions(const char *soap_endpoint, const char *soap_action, _ns9__GetOSDOptions *ns9__GetOSDOptions, _ns9__GetOSDOptionsResponse &ns9__GetOSDOptionsResponse);
        /// Web service operation 'SetOSD' (returns SOAP_OK or error code)
        virtual int SetOSD(_ns9__SetOSD *ns9__SetOSD, _ns9__SetOSDResponse &ns9__SetOSDResponse)
        { return this->SetOSD(NULL, NULL, ns9__SetOSD, ns9__SetOSDResponse); }
        virtual int SetOSD(const char *soap_endpoint, const char *soap_action, _ns9__SetOSD *ns9__SetOSD, _ns9__SetOSDResponse &ns9__SetOSDResponse);
        /// Web service operation 'CreateOSD' (returns SOAP_OK or error code)
        virtual int CreateOSD(_ns9__CreateOSD *ns9__CreateOSD, _ns9__CreateOSDResponse &ns9__CreateOSDResponse)
        { return this->CreateOSD(NULL, NULL, ns9__CreateOSD, ns9__CreateOSDResponse); }
        virtual int CreateOSD(const char *soap_endpoint, const char *soap_action, _ns9__CreateOSD *ns9__CreateOSD, _ns9__CreateOSDResponse &ns9__CreateOSDResponse);
        /// Web service operation 'DeleteOSD' (returns SOAP_OK or error code)
        virtual int DeleteOSD(_ns9__DeleteOSD *ns9__DeleteOSD, _ns9__DeleteOSDResponse &ns9__DeleteOSDResponse)
        { return this->DeleteOSD(NULL, NULL, ns9__DeleteOSD, ns9__DeleteOSDResponse); }
        virtual int DeleteOSD(const char *soap_endpoint, const char *soap_action, _ns9__DeleteOSD *ns9__DeleteOSD, _ns9__DeleteOSDResponse &ns9__DeleteOSDResponse);
    };
#endif
