/* soapCredentialBindingProxy.cpp
   Generated by gSOAP 2.8.40 for onvifgen/onvif.h

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#include "soapCredentialBindingProxy.h"

CredentialBindingProxy::CredentialBindingProxy()
{	this->soap = soap_new();
	this->soap_own = true;
	CredentialBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

CredentialBindingProxy::CredentialBindingProxy(const CredentialBindingProxy& rhs)
{	this->soap = rhs.soap;
	this->soap_own = false;
	this->soap_endpoint = rhs.soap_endpoint;
}

CredentialBindingProxy::CredentialBindingProxy(struct soap *_soap)
{	this->soap = _soap;
	this->soap_own = false;
	CredentialBindingProxy_init(_soap->imode, _soap->omode);
}

CredentialBindingProxy::CredentialBindingProxy(const char *endpoint)
{	this->soap = soap_new();
	this->soap_own = true;
	CredentialBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = endpoint;
}

CredentialBindingProxy::CredentialBindingProxy(soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	CredentialBindingProxy_init(iomode, iomode);
}

CredentialBindingProxy::CredentialBindingProxy(const char *endpoint, soap_mode iomode)
{	this->soap = soap_new();
	this->soap_own = true;
	CredentialBindingProxy_init(iomode, iomode);
	soap_endpoint = endpoint;
}

CredentialBindingProxy::CredentialBindingProxy(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->soap_own = true;
	CredentialBindingProxy_init(imode, omode);
}

CredentialBindingProxy::~CredentialBindingProxy()
{	if (this->soap_own)
		soap_free(this->soap);
}

void CredentialBindingProxy::CredentialBindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] = {
        {"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
        {"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
        {"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
        {"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
        {"c14n", "http://www.w3.org/2001/10/xml-exc-c14n#", NULL, NULL},
        {"ds", "http://www.w3.org/2000/09/xmldsig#", NULL, NULL},
        {"saml1", "urn:oasis:names:tc:SAML:1.0:assertion", NULL, NULL},
        {"saml2", "urn:oasis:names:tc:SAML:2.0:assertion", NULL, NULL},
        {"wsu", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd", NULL, NULL},
        {"xenc", "http://www.w3.org/2001/04/xmlenc#", NULL, NULL},
        {"wsc", "http://docs.oasis-open.org/ws-sx/ws-secureconversation/200512", NULL, NULL},
        {"wsse", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd", "http://docs.oasis-open.org/wss/oasis-wss-wssecurity-secext-1.1.xsd", NULL},
        {"ns13", "http://www.onvif.org/ver10/pacs", NULL, NULL},
        {"ns14", "http://www.w3.org/2005/08/addressing", NULL, NULL},
        {"xmime", "http://www.w3.org/2005/05/xmlmime", NULL, NULL},
        {"ns4", "http://www.w3.org/2004/08/xop/include", NULL, NULL},
        {"ns2", "http://www.onvif.org/ver10/schema", NULL, NULL},
        {"ns3", "http://docs.oasis-open.org/wsn/b-2", NULL, NULL},
        {"ns5", "http://docs.oasis-open.org/wsrf/bf-2", NULL, NULL},
        {"ns6", "http://docs.oasis-open.org/wsn/t-1", NULL, NULL},
        {"ns1", "http://www.onvif.org/ver10/device/wsdl", NULL, NULL},
        {"ns10", "http://www.onvif.org/ver20/media/wsdl", NULL, NULL},
        {"ns11", "http://www.onvif.org/ver20/ptz/wsdl", NULL, NULL},
        {"ns12", "http://www.onvif.org/ver10/credential/wsdl", NULL, NULL},
        {"ns7", "http://www.onvif.org/ver10/display/wsdl", NULL, NULL},
        {"ns8", "http://www.onvif.org/ver20/imaging/wsdl", NULL, NULL},
        {"ns9", "http://www.onvif.org/ver10/media/wsdl", NULL, NULL},
        {NULL, NULL, NULL, NULL}
    };
	soap_set_namespaces(this->soap, namespaces);
}

#ifndef WITH_PURE_VIRTUAL
CredentialBindingProxy *CredentialBindingProxy::copy()
{	CredentialBindingProxy *dup = SOAP_NEW_COPY(CredentialBindingProxy);
	if (dup)
		soap_copy_context(dup->soap, this->soap);
	return dup;
}
#endif

CredentialBindingProxy& CredentialBindingProxy::operator=(const CredentialBindingProxy& rhs)
{	if (this->soap_own)
		soap_free(this->soap);
	this->soap = rhs.soap;
	this->soap_own = false;
	this->soap_endpoint = rhs.soap_endpoint;
	return *this;
}

void CredentialBindingProxy::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void CredentialBindingProxy::reset()
{	this->destroy();
	soap_done(this->soap);
	soap_initialize(this->soap);
	CredentialBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

void CredentialBindingProxy::soap_noheader()
{	this->soap->header = NULL;
}

void CredentialBindingProxy::soap_header(struct _wsse__Security *wsse__Security)
{	::soap_header(this->soap);
	this->soap->header->wsse__Security = wsse__Security;
}

::SOAP_ENV__Header *CredentialBindingProxy::soap_header()
{	return this->soap->header;
}

::SOAP_ENV__Fault *CredentialBindingProxy::soap_fault()
{	return this->soap->fault;
}

const char *CredentialBindingProxy::soap_fault_string()
{	return *soap_faultstring(this->soap);
}

const char *CredentialBindingProxy::soap_fault_detail()
{	return *soap_faultdetail(this->soap);
}

int CredentialBindingProxy::soap_close_socket()
{	return soap_closesock(this->soap);
}

int CredentialBindingProxy::soap_force_close_socket()
{	return soap_force_closesock(this->soap);
}

void CredentialBindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
#ifndef WITH_COMPAT
void CredentialBindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}
#endif

char *CredentialBindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

int CredentialBindingProxy::GetServiceCapabilities(const char *endpoint, const char *soap_action, _ns12__GetServiceCapabilities *ns12__GetServiceCapabilities, _ns12__GetServiceCapabilitiesResponse &ns12__GetServiceCapabilitiesResponse)
{	struct soap *soap = this->soap;
	struct __ns12__GetServiceCapabilities soap_tmp___ns12__GetServiceCapabilities;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/GetServiceCapabilities";
	soap_tmp___ns12__GetServiceCapabilities.ns12__GetServiceCapabilities = ns12__GetServiceCapabilities;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns12__GetServiceCapabilities(soap, &soap_tmp___ns12__GetServiceCapabilities);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns12__GetServiceCapabilities(soap, &soap_tmp___ns12__GetServiceCapabilities, "-ns12:GetServiceCapabilities", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns12__GetServiceCapabilities(soap, &soap_tmp___ns12__GetServiceCapabilities, "-ns12:GetServiceCapabilities", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns12__GetServiceCapabilitiesResponse*>(&ns12__GetServiceCapabilitiesResponse)) // NULL ref?
		return soap_closesock(soap);
	ns12__GetServiceCapabilitiesResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns12__GetServiceCapabilitiesResponse.soap_get(soap, "ns12:GetServiceCapabilitiesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::GetSupportedFormatTypes(const char *endpoint, const char *soap_action, _ns12__GetSupportedFormatTypes *ns12__GetSupportedFormatTypes, _ns12__GetSupportedFormatTypesResponse &ns12__GetSupportedFormatTypesResponse)
{	struct soap *soap = this->soap;
	struct __ns12__GetSupportedFormatTypes soap_tmp___ns12__GetSupportedFormatTypes;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/GetSupportedFormatTypes";
	soap_tmp___ns12__GetSupportedFormatTypes.ns12__GetSupportedFormatTypes = ns12__GetSupportedFormatTypes;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns12__GetSupportedFormatTypes(soap, &soap_tmp___ns12__GetSupportedFormatTypes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns12__GetSupportedFormatTypes(soap, &soap_tmp___ns12__GetSupportedFormatTypes, "-ns12:GetSupportedFormatTypes", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns12__GetSupportedFormatTypes(soap, &soap_tmp___ns12__GetSupportedFormatTypes, "-ns12:GetSupportedFormatTypes", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns12__GetSupportedFormatTypesResponse*>(&ns12__GetSupportedFormatTypesResponse)) // NULL ref?
		return soap_closesock(soap);
	ns12__GetSupportedFormatTypesResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns12__GetSupportedFormatTypesResponse.soap_get(soap, "ns12:GetSupportedFormatTypesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::GetCredentialInfo(const char *endpoint, const char *soap_action, _ns12__GetCredentialInfo *ns12__GetCredentialInfo, _ns12__GetCredentialInfoResponse &ns12__GetCredentialInfoResponse)
{	struct soap *soap = this->soap;
	struct __ns12__GetCredentialInfo soap_tmp___ns12__GetCredentialInfo;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/GetCredentialInfo";
	soap_tmp___ns12__GetCredentialInfo.ns12__GetCredentialInfo = ns12__GetCredentialInfo;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns12__GetCredentialInfo(soap, &soap_tmp___ns12__GetCredentialInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns12__GetCredentialInfo(soap, &soap_tmp___ns12__GetCredentialInfo, "-ns12:GetCredentialInfo", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns12__GetCredentialInfo(soap, &soap_tmp___ns12__GetCredentialInfo, "-ns12:GetCredentialInfo", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns12__GetCredentialInfoResponse*>(&ns12__GetCredentialInfoResponse)) // NULL ref?
		return soap_closesock(soap);
	ns12__GetCredentialInfoResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns12__GetCredentialInfoResponse.soap_get(soap, "ns12:GetCredentialInfoResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::GetCredentialInfoList(const char *endpoint, const char *soap_action, _ns12__GetCredentialInfoList *ns12__GetCredentialInfoList, _ns12__GetCredentialInfoListResponse &ns12__GetCredentialInfoListResponse)
{	struct soap *soap = this->soap;
	struct __ns12__GetCredentialInfoList soap_tmp___ns12__GetCredentialInfoList;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/GetCredentialInfoList";
	soap_tmp___ns12__GetCredentialInfoList.ns12__GetCredentialInfoList = ns12__GetCredentialInfoList;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns12__GetCredentialInfoList(soap, &soap_tmp___ns12__GetCredentialInfoList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns12__GetCredentialInfoList(soap, &soap_tmp___ns12__GetCredentialInfoList, "-ns12:GetCredentialInfoList", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns12__GetCredentialInfoList(soap, &soap_tmp___ns12__GetCredentialInfoList, "-ns12:GetCredentialInfoList", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns12__GetCredentialInfoListResponse*>(&ns12__GetCredentialInfoListResponse)) // NULL ref?
		return soap_closesock(soap);
	ns12__GetCredentialInfoListResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns12__GetCredentialInfoListResponse.soap_get(soap, "ns12:GetCredentialInfoListResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::GetCredentials(const char *endpoint, const char *soap_action, _ns12__GetCredentials *ns12__GetCredentials, _ns12__GetCredentialsResponse &ns12__GetCredentialsResponse)
{	struct soap *soap = this->soap;
	struct __ns12__GetCredentials soap_tmp___ns12__GetCredentials;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/GetCredentials";
	soap_tmp___ns12__GetCredentials.ns12__GetCredentials = ns12__GetCredentials;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns12__GetCredentials(soap, &soap_tmp___ns12__GetCredentials);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns12__GetCredentials(soap, &soap_tmp___ns12__GetCredentials, "-ns12:GetCredentials", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns12__GetCredentials(soap, &soap_tmp___ns12__GetCredentials, "-ns12:GetCredentials", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns12__GetCredentialsResponse*>(&ns12__GetCredentialsResponse)) // NULL ref?
		return soap_closesock(soap);
	ns12__GetCredentialsResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns12__GetCredentialsResponse.soap_get(soap, "ns12:GetCredentialsResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::GetCredentialList(const char *endpoint, const char *soap_action, _ns12__GetCredentialList *ns12__GetCredentialList, _ns12__GetCredentialListResponse &ns12__GetCredentialListResponse)
{	struct soap *soap = this->soap;
	struct __ns12__GetCredentialList soap_tmp___ns12__GetCredentialList;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/GetCredentialList";
	soap_tmp___ns12__GetCredentialList.ns12__GetCredentialList = ns12__GetCredentialList;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns12__GetCredentialList(soap, &soap_tmp___ns12__GetCredentialList);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns12__GetCredentialList(soap, &soap_tmp___ns12__GetCredentialList, "-ns12:GetCredentialList", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns12__GetCredentialList(soap, &soap_tmp___ns12__GetCredentialList, "-ns12:GetCredentialList", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns12__GetCredentialListResponse*>(&ns12__GetCredentialListResponse)) // NULL ref?
		return soap_closesock(soap);
	ns12__GetCredentialListResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns12__GetCredentialListResponse.soap_get(soap, "ns12:GetCredentialListResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::CreateCredential(const char *endpoint, const char *soap_action, _ns12__CreateCredential *ns12__CreateCredential, _ns12__CreateCredentialResponse &ns12__CreateCredentialResponse)
{	struct soap *soap = this->soap;
	struct __ns12__CreateCredential soap_tmp___ns12__CreateCredential;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/CreateCredential";
	soap_tmp___ns12__CreateCredential.ns12__CreateCredential = ns12__CreateCredential;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns12__CreateCredential(soap, &soap_tmp___ns12__CreateCredential);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns12__CreateCredential(soap, &soap_tmp___ns12__CreateCredential, "-ns12:CreateCredential", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns12__CreateCredential(soap, &soap_tmp___ns12__CreateCredential, "-ns12:CreateCredential", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns12__CreateCredentialResponse*>(&ns12__CreateCredentialResponse)) // NULL ref?
		return soap_closesock(soap);
	ns12__CreateCredentialResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns12__CreateCredentialResponse.soap_get(soap, "ns12:CreateCredentialResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::ModifyCredential(const char *endpoint, const char *soap_action, _ns12__ModifyCredential *ns12__ModifyCredential, _ns12__ModifyCredentialResponse &ns12__ModifyCredentialResponse)
{	struct soap *soap = this->soap;
	struct __ns12__ModifyCredential soap_tmp___ns12__ModifyCredential;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/ModifyCredential";
	soap_tmp___ns12__ModifyCredential.ns12__ModifyCredential = ns12__ModifyCredential;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns12__ModifyCredential(soap, &soap_tmp___ns12__ModifyCredential);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns12__ModifyCredential(soap, &soap_tmp___ns12__ModifyCredential, "-ns12:ModifyCredential", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns12__ModifyCredential(soap, &soap_tmp___ns12__ModifyCredential, "-ns12:ModifyCredential", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns12__ModifyCredentialResponse*>(&ns12__ModifyCredentialResponse)) // NULL ref?
		return soap_closesock(soap);
	ns12__ModifyCredentialResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns12__ModifyCredentialResponse.soap_get(soap, "ns12:ModifyCredentialResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::DeleteCredential(const char *endpoint, const char *soap_action, _ns12__DeleteCredential *ns12__DeleteCredential, _ns12__DeleteCredentialResponse &ns12__DeleteCredentialResponse)
{	struct soap *soap = this->soap;
	struct __ns12__DeleteCredential soap_tmp___ns12__DeleteCredential;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/DeleteCredential";
	soap_tmp___ns12__DeleteCredential.ns12__DeleteCredential = ns12__DeleteCredential;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns12__DeleteCredential(soap, &soap_tmp___ns12__DeleteCredential);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns12__DeleteCredential(soap, &soap_tmp___ns12__DeleteCredential, "-ns12:DeleteCredential", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns12__DeleteCredential(soap, &soap_tmp___ns12__DeleteCredential, "-ns12:DeleteCredential", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns12__DeleteCredentialResponse*>(&ns12__DeleteCredentialResponse)) // NULL ref?
		return soap_closesock(soap);
	ns12__DeleteCredentialResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns12__DeleteCredentialResponse.soap_get(soap, "ns12:DeleteCredentialResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::GetCredentialState(const char *endpoint, const char *soap_action, _ns12__GetCredentialState *ns12__GetCredentialState, _ns12__GetCredentialStateResponse &ns12__GetCredentialStateResponse)
{	struct soap *soap = this->soap;
	struct __ns12__GetCredentialState soap_tmp___ns12__GetCredentialState;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/GetCredentialState";
	soap_tmp___ns12__GetCredentialState.ns12__GetCredentialState = ns12__GetCredentialState;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns12__GetCredentialState(soap, &soap_tmp___ns12__GetCredentialState);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns12__GetCredentialState(soap, &soap_tmp___ns12__GetCredentialState, "-ns12:GetCredentialState", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns12__GetCredentialState(soap, &soap_tmp___ns12__GetCredentialState, "-ns12:GetCredentialState", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns12__GetCredentialStateResponse*>(&ns12__GetCredentialStateResponse)) // NULL ref?
		return soap_closesock(soap);
	ns12__GetCredentialStateResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns12__GetCredentialStateResponse.soap_get(soap, "ns12:GetCredentialStateResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::EnableCredential(const char *endpoint, const char *soap_action, _ns12__EnableCredential *ns12__EnableCredential, _ns12__EnableCredentialResponse &ns12__EnableCredentialResponse)
{	struct soap *soap = this->soap;
	struct __ns12__EnableCredential soap_tmp___ns12__EnableCredential;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/EnableCredential";
	soap_tmp___ns12__EnableCredential.ns12__EnableCredential = ns12__EnableCredential;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns12__EnableCredential(soap, &soap_tmp___ns12__EnableCredential);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns12__EnableCredential(soap, &soap_tmp___ns12__EnableCredential, "-ns12:EnableCredential", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns12__EnableCredential(soap, &soap_tmp___ns12__EnableCredential, "-ns12:EnableCredential", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns12__EnableCredentialResponse*>(&ns12__EnableCredentialResponse)) // NULL ref?
		return soap_closesock(soap);
	ns12__EnableCredentialResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns12__EnableCredentialResponse.soap_get(soap, "ns12:EnableCredentialResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::DisableCredential(const char *endpoint, const char *soap_action, _ns12__DisableCredential *ns12__DisableCredential, _ns12__DisableCredentialResponse &ns12__DisableCredentialResponse)
{	struct soap *soap = this->soap;
	struct __ns12__DisableCredential soap_tmp___ns12__DisableCredential;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/DisableCredential";
	soap_tmp___ns12__DisableCredential.ns12__DisableCredential = ns12__DisableCredential;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns12__DisableCredential(soap, &soap_tmp___ns12__DisableCredential);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns12__DisableCredential(soap, &soap_tmp___ns12__DisableCredential, "-ns12:DisableCredential", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns12__DisableCredential(soap, &soap_tmp___ns12__DisableCredential, "-ns12:DisableCredential", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns12__DisableCredentialResponse*>(&ns12__DisableCredentialResponse)) // NULL ref?
		return soap_closesock(soap);
	ns12__DisableCredentialResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns12__DisableCredentialResponse.soap_get(soap, "ns12:DisableCredentialResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::ResetAntipassbackViolation(const char *endpoint, const char *soap_action, _ns12__ResetAntipassbackViolation *ns12__ResetAntipassbackViolation, _ns12__ResetAntipassbackViolationResponse &ns12__ResetAntipassbackViolationResponse)
{	struct soap *soap = this->soap;
	struct __ns12__ResetAntipassbackViolation soap_tmp___ns12__ResetAntipassbackViolation;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/ResetAntipassbackViolation";
	soap_tmp___ns12__ResetAntipassbackViolation.ns12__ResetAntipassbackViolation = ns12__ResetAntipassbackViolation;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns12__ResetAntipassbackViolation(soap, &soap_tmp___ns12__ResetAntipassbackViolation);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns12__ResetAntipassbackViolation(soap, &soap_tmp___ns12__ResetAntipassbackViolation, "-ns12:ResetAntipassbackViolation", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns12__ResetAntipassbackViolation(soap, &soap_tmp___ns12__ResetAntipassbackViolation, "-ns12:ResetAntipassbackViolation", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns12__ResetAntipassbackViolationResponse*>(&ns12__ResetAntipassbackViolationResponse)) // NULL ref?
		return soap_closesock(soap);
	ns12__ResetAntipassbackViolationResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns12__ResetAntipassbackViolationResponse.soap_get(soap, "ns12:ResetAntipassbackViolationResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::GetCredentialIdentifiers(const char *endpoint, const char *soap_action, _ns12__GetCredentialIdentifiers *ns12__GetCredentialIdentifiers, _ns12__GetCredentialIdentifiersResponse &ns12__GetCredentialIdentifiersResponse)
{	struct soap *soap = this->soap;
	struct __ns12__GetCredentialIdentifiers soap_tmp___ns12__GetCredentialIdentifiers;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/GetCredentialIdentifiers";
	soap_tmp___ns12__GetCredentialIdentifiers.ns12__GetCredentialIdentifiers = ns12__GetCredentialIdentifiers;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns12__GetCredentialIdentifiers(soap, &soap_tmp___ns12__GetCredentialIdentifiers);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns12__GetCredentialIdentifiers(soap, &soap_tmp___ns12__GetCredentialIdentifiers, "-ns12:GetCredentialIdentifiers", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns12__GetCredentialIdentifiers(soap, &soap_tmp___ns12__GetCredentialIdentifiers, "-ns12:GetCredentialIdentifiers", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns12__GetCredentialIdentifiersResponse*>(&ns12__GetCredentialIdentifiersResponse)) // NULL ref?
		return soap_closesock(soap);
	ns12__GetCredentialIdentifiersResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns12__GetCredentialIdentifiersResponse.soap_get(soap, "ns12:GetCredentialIdentifiersResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::SetCredentialIdentifier(const char *endpoint, const char *soap_action, _ns12__SetCredentialIdentifier *ns12__SetCredentialIdentifier, _ns12__SetCredentialIdentifierResponse &ns12__SetCredentialIdentifierResponse)
{	struct soap *soap = this->soap;
	struct __ns12__SetCredentialIdentifier soap_tmp___ns12__SetCredentialIdentifier;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/SetCredentialIdentifier";
	soap_tmp___ns12__SetCredentialIdentifier.ns12__SetCredentialIdentifier = ns12__SetCredentialIdentifier;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns12__SetCredentialIdentifier(soap, &soap_tmp___ns12__SetCredentialIdentifier);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns12__SetCredentialIdentifier(soap, &soap_tmp___ns12__SetCredentialIdentifier, "-ns12:SetCredentialIdentifier", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns12__SetCredentialIdentifier(soap, &soap_tmp___ns12__SetCredentialIdentifier, "-ns12:SetCredentialIdentifier", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns12__SetCredentialIdentifierResponse*>(&ns12__SetCredentialIdentifierResponse)) // NULL ref?
		return soap_closesock(soap);
	ns12__SetCredentialIdentifierResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns12__SetCredentialIdentifierResponse.soap_get(soap, "ns12:SetCredentialIdentifierResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::DeleteCredentialIdentifier(const char *endpoint, const char *soap_action, _ns12__DeleteCredentialIdentifier *ns12__DeleteCredentialIdentifier, _ns12__DeleteCredentialIdentifierResponse &ns12__DeleteCredentialIdentifierResponse)
{	struct soap *soap = this->soap;
	struct __ns12__DeleteCredentialIdentifier soap_tmp___ns12__DeleteCredentialIdentifier;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/DeleteCredentialIdentifier";
	soap_tmp___ns12__DeleteCredentialIdentifier.ns12__DeleteCredentialIdentifier = ns12__DeleteCredentialIdentifier;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns12__DeleteCredentialIdentifier(soap, &soap_tmp___ns12__DeleteCredentialIdentifier);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns12__DeleteCredentialIdentifier(soap, &soap_tmp___ns12__DeleteCredentialIdentifier, "-ns12:DeleteCredentialIdentifier", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns12__DeleteCredentialIdentifier(soap, &soap_tmp___ns12__DeleteCredentialIdentifier, "-ns12:DeleteCredentialIdentifier", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns12__DeleteCredentialIdentifierResponse*>(&ns12__DeleteCredentialIdentifierResponse)) // NULL ref?
		return soap_closesock(soap);
	ns12__DeleteCredentialIdentifierResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns12__DeleteCredentialIdentifierResponse.soap_get(soap, "ns12:DeleteCredentialIdentifierResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::GetCredentialAccessProfiles(const char *endpoint, const char *soap_action, _ns12__GetCredentialAccessProfiles *ns12__GetCredentialAccessProfiles, _ns12__GetCredentialAccessProfilesResponse &ns12__GetCredentialAccessProfilesResponse)
{	struct soap *soap = this->soap;
	struct __ns12__GetCredentialAccessProfiles soap_tmp___ns12__GetCredentialAccessProfiles;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/GetCredentialAccessProfiles";
	soap_tmp___ns12__GetCredentialAccessProfiles.ns12__GetCredentialAccessProfiles = ns12__GetCredentialAccessProfiles;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns12__GetCredentialAccessProfiles(soap, &soap_tmp___ns12__GetCredentialAccessProfiles);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns12__GetCredentialAccessProfiles(soap, &soap_tmp___ns12__GetCredentialAccessProfiles, "-ns12:GetCredentialAccessProfiles", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns12__GetCredentialAccessProfiles(soap, &soap_tmp___ns12__GetCredentialAccessProfiles, "-ns12:GetCredentialAccessProfiles", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns12__GetCredentialAccessProfilesResponse*>(&ns12__GetCredentialAccessProfilesResponse)) // NULL ref?
		return soap_closesock(soap);
	ns12__GetCredentialAccessProfilesResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns12__GetCredentialAccessProfilesResponse.soap_get(soap, "ns12:GetCredentialAccessProfilesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::SetCredentialAccessProfiles(const char *endpoint, const char *soap_action, _ns12__SetCredentialAccessProfiles *ns12__SetCredentialAccessProfiles, _ns12__SetCredentialAccessProfilesResponse &ns12__SetCredentialAccessProfilesResponse)
{	struct soap *soap = this->soap;
	struct __ns12__SetCredentialAccessProfiles soap_tmp___ns12__SetCredentialAccessProfiles;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/SetCredentialAccessProfiles";
	soap_tmp___ns12__SetCredentialAccessProfiles.ns12__SetCredentialAccessProfiles = ns12__SetCredentialAccessProfiles;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns12__SetCredentialAccessProfiles(soap, &soap_tmp___ns12__SetCredentialAccessProfiles);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns12__SetCredentialAccessProfiles(soap, &soap_tmp___ns12__SetCredentialAccessProfiles, "-ns12:SetCredentialAccessProfiles", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns12__SetCredentialAccessProfiles(soap, &soap_tmp___ns12__SetCredentialAccessProfiles, "-ns12:SetCredentialAccessProfiles", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns12__SetCredentialAccessProfilesResponse*>(&ns12__SetCredentialAccessProfilesResponse)) // NULL ref?
		return soap_closesock(soap);
	ns12__SetCredentialAccessProfilesResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns12__SetCredentialAccessProfilesResponse.soap_get(soap, "ns12:SetCredentialAccessProfilesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int CredentialBindingProxy::DeleteCredentialAccessProfiles(const char *endpoint, const char *soap_action, _ns12__DeleteCredentialAccessProfiles *ns12__DeleteCredentialAccessProfiles, _ns12__DeleteCredentialAccessProfilesResponse &ns12__DeleteCredentialAccessProfilesResponse)
{	struct soap *soap = this->soap;
	struct __ns12__DeleteCredentialAccessProfiles soap_tmp___ns12__DeleteCredentialAccessProfiles;
	if (endpoint)
		soap_endpoint = endpoint;
	if (soap_action == NULL)
		soap_action = "http://www.onvif.org/ver10/credential/wsdl/DeleteCredentialAccessProfiles";
	soap_tmp___ns12__DeleteCredentialAccessProfiles.ns12__DeleteCredentialAccessProfiles = ns12__DeleteCredentialAccessProfiles;
	soap_begin(soap);
	soap_set_version(soap, 2); /* SOAP1.2 */
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns12__DeleteCredentialAccessProfiles(soap, &soap_tmp___ns12__DeleteCredentialAccessProfiles);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns12__DeleteCredentialAccessProfiles(soap, &soap_tmp___ns12__DeleteCredentialAccessProfiles, "-ns12:DeleteCredentialAccessProfiles", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns12__DeleteCredentialAccessProfiles(soap, &soap_tmp___ns12__DeleteCredentialAccessProfiles, "-ns12:DeleteCredentialAccessProfiles", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!static_cast<_ns12__DeleteCredentialAccessProfilesResponse*>(&ns12__DeleteCredentialAccessProfilesResponse)) // NULL ref?
		return soap_closesock(soap);
	ns12__DeleteCredentialAccessProfilesResponse.soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns12__DeleteCredentialAccessProfilesResponse.soap_get(soap, "ns12:DeleteCredentialAccessProfilesResponse", NULL);
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
