/* soapMedia2BindingProxy.h
   Generated by gSOAP 2.8.40 for onvifgen/onvif.h

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapMedia2BindingProxy_H
#define soapMedia2BindingProxy_H
#include "soapH.h"

    class SOAP_CMAC Media2BindingProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        bool soap_own; ///< flag indicating that this context is owned by this proxy when context is shared
        /// Endpoint URL of service 'Media2BindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in onvifgen/onvif.h, if any
        /// Construct a proxy with new managing context
        Media2BindingProxy();
        /// Copy constructor
        Media2BindingProxy(const Media2BindingProxy& rhs);
        /// Construct proxy given a shared managing context
        Media2BindingProxy(struct soap*);
        /// Constructor taking an endpoint URL
        Media2BindingProxy(const char *endpoint);
        /// Constructor taking input and output mode flags for the new managing context
        Media2BindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        Media2BindingProxy(const char *endpoint, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        Media2BindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes non-shared managing context only (use destroy() to delete deserialized data)
        virtual ~Media2BindingProxy();
        /// Initializer used by constructors
        virtual void Media2BindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual Media2BindingProxy *copy() SOAP_PURE_VIRTUAL;
        /// Copy assignment
        Media2BindingProxy& operator=(const Media2BindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Add SOAP Header to message
        virtual void soap_header(struct _wsse__Security *wsse__Security);
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault string (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail as string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Web service operation 'GetServiceCapabilities' (returns SOAP_OK or error code)
        virtual int GetServiceCapabilities(_ns10__GetServiceCapabilities *ns10__GetServiceCapabilities, _ns10__GetServiceCapabilitiesResponse2 &ns10__GetServiceCapabilitiesResponse2)
        { return this->GetServiceCapabilities(NULL, NULL, ns10__GetServiceCapabilities, ns10__GetServiceCapabilitiesResponse2); }
        virtual int GetServiceCapabilities(const char *soap_endpoint, const char *soap_action, _ns10__GetServiceCapabilities *ns10__GetServiceCapabilities, _ns10__GetServiceCapabilitiesResponse2 &ns10__GetServiceCapabilitiesResponse2);
        /// Web service operation 'CreateProfile' (returns SOAP_OK or error code)
        virtual int CreateProfile(_ns10__CreateProfile *ns10__CreateProfile, _ns10__CreateProfileResponse &ns10__CreateProfileResponse)
        { return this->CreateProfile(NULL, NULL, ns10__CreateProfile, ns10__CreateProfileResponse); }
        virtual int CreateProfile(const char *soap_endpoint, const char *soap_action, _ns10__CreateProfile *ns10__CreateProfile, _ns10__CreateProfileResponse &ns10__CreateProfileResponse);
        /// Web service operation 'GetProfiles' (returns SOAP_OK or error code)
        virtual int GetProfiles(_ns10__GetProfiles *ns10__GetProfiles, _ns10__GetProfilesResponse &ns10__GetProfilesResponse)
        { return this->GetProfiles(NULL, NULL, ns10__GetProfiles, ns10__GetProfilesResponse); }
        virtual int GetProfiles(const char *soap_endpoint, const char *soap_action, _ns10__GetProfiles *ns10__GetProfiles, _ns10__GetProfilesResponse &ns10__GetProfilesResponse);
        /// Web service operation 'AddConfiguration' (returns SOAP_OK or error code)
        virtual int AddConfiguration(_ns10__AddConfiguration *ns10__AddConfiguration, _ns10__AddConfigurationResponse &ns10__AddConfigurationResponse)
        { return this->AddConfiguration(NULL, NULL, ns10__AddConfiguration, ns10__AddConfigurationResponse); }
        virtual int AddConfiguration(const char *soap_endpoint, const char *soap_action, _ns10__AddConfiguration *ns10__AddConfiguration, _ns10__AddConfigurationResponse &ns10__AddConfigurationResponse);
        /// Web service operation 'RemoveConfiguration' (returns SOAP_OK or error code)
        virtual int RemoveConfiguration(_ns10__RemoveConfiguration *ns10__RemoveConfiguration, _ns10__RemoveConfigurationResponse &ns10__RemoveConfigurationResponse)
        { return this->RemoveConfiguration(NULL, NULL, ns10__RemoveConfiguration, ns10__RemoveConfigurationResponse); }
        virtual int RemoveConfiguration(const char *soap_endpoint, const char *soap_action, _ns10__RemoveConfiguration *ns10__RemoveConfiguration, _ns10__RemoveConfigurationResponse &ns10__RemoveConfigurationResponse);
        /// Web service operation 'DeleteProfile' (returns SOAP_OK or error code)
        virtual int DeleteProfile(_ns10__DeleteProfile *ns10__DeleteProfile, _ns10__DeleteProfileResponse &ns10__DeleteProfileResponse)
        { return this->DeleteProfile(NULL, NULL, ns10__DeleteProfile, ns10__DeleteProfileResponse); }
        virtual int DeleteProfile(const char *soap_endpoint, const char *soap_action, _ns10__DeleteProfile *ns10__DeleteProfile, _ns10__DeleteProfileResponse &ns10__DeleteProfileResponse);
        /// Web service operation 'GetVideoSourceConfigurations' (returns SOAP_OK or error code)
        virtual int GetVideoSourceConfigurations(ns10__GetConfiguration *ns10__GetVideoSourceConfigurations, _ns10__GetVideoSourceConfigurationsResponse &ns10__GetVideoSourceConfigurationsResponse)
        { return this->GetVideoSourceConfigurations(NULL, NULL, ns10__GetVideoSourceConfigurations, ns10__GetVideoSourceConfigurationsResponse); }
        virtual int GetVideoSourceConfigurations(const char *soap_endpoint, const char *soap_action, ns10__GetConfiguration *ns10__GetVideoSourceConfigurations, _ns10__GetVideoSourceConfigurationsResponse &ns10__GetVideoSourceConfigurationsResponse);
        /// Web service operation 'GetVideoEncoderConfigurations' (returns SOAP_OK or error code)
        virtual int GetVideoEncoderConfigurations(ns10__GetConfiguration *ns10__GetVideoEncoderConfigurations, _ns10__GetVideoEncoderConfigurationsResponse &ns10__GetVideoEncoderConfigurationsResponse)
        { return this->GetVideoEncoderConfigurations(NULL, NULL, ns10__GetVideoEncoderConfigurations, ns10__GetVideoEncoderConfigurationsResponse); }
        virtual int GetVideoEncoderConfigurations(const char *soap_endpoint, const char *soap_action, ns10__GetConfiguration *ns10__GetVideoEncoderConfigurations, _ns10__GetVideoEncoderConfigurationsResponse &ns10__GetVideoEncoderConfigurationsResponse);
        /// Web service operation 'GetAudioSourceConfigurations' (returns SOAP_OK or error code)
        virtual int GetAudioSourceConfigurations(ns10__GetConfiguration *ns10__GetAudioSourceConfigurations, _ns10__GetAudioSourceConfigurationsResponse &ns10__GetAudioSourceConfigurationsResponse)
        { return this->GetAudioSourceConfigurations(NULL, NULL, ns10__GetAudioSourceConfigurations, ns10__GetAudioSourceConfigurationsResponse); }
        virtual int GetAudioSourceConfigurations(const char *soap_endpoint, const char *soap_action, ns10__GetConfiguration *ns10__GetAudioSourceConfigurations, _ns10__GetAudioSourceConfigurationsResponse &ns10__GetAudioSourceConfigurationsResponse);
        /// Web service operation 'GetAudioEncoderConfigurations' (returns SOAP_OK or error code)
        virtual int GetAudioEncoderConfigurations(ns10__GetConfiguration *ns10__GetAudioEncoderConfigurations, _ns10__GetAudioEncoderConfigurationsResponse &ns10__GetAudioEncoderConfigurationsResponse)
        { return this->GetAudioEncoderConfigurations(NULL, NULL, ns10__GetAudioEncoderConfigurations, ns10__GetAudioEncoderConfigurationsResponse); }
        virtual int GetAudioEncoderConfigurations(const char *soap_endpoint, const char *soap_action, ns10__GetConfiguration *ns10__GetAudioEncoderConfigurations, _ns10__GetAudioEncoderConfigurationsResponse &ns10__GetAudioEncoderConfigurationsResponse);
        /// Web service operation 'GetAnalyticsConfigurations' (returns SOAP_OK or error code)
        virtual int GetAnalyticsConfigurations(ns10__GetConfiguration *ns10__GetAnalyticsConfigurations, _ns10__GetAnalyticsConfigurationsResponse &ns10__GetAnalyticsConfigurationsResponse)
        { return this->GetAnalyticsConfigurations(NULL, NULL, ns10__GetAnalyticsConfigurations, ns10__GetAnalyticsConfigurationsResponse); }
        virtual int GetAnalyticsConfigurations(const char *soap_endpoint, const char *soap_action, ns10__GetConfiguration *ns10__GetAnalyticsConfigurations, _ns10__GetAnalyticsConfigurationsResponse &ns10__GetAnalyticsConfigurationsResponse);
        /// Web service operation 'GetMetadataConfigurations' (returns SOAP_OK or error code)
        virtual int GetMetadataConfigurations(ns10__GetConfiguration *ns10__GetMetadataConfigurations, _ns10__GetMetadataConfigurationsResponse &ns10__GetMetadataConfigurationsResponse)
        { return this->GetMetadataConfigurations(NULL, NULL, ns10__GetMetadataConfigurations, ns10__GetMetadataConfigurationsResponse); }
        virtual int GetMetadataConfigurations(const char *soap_endpoint, const char *soap_action, ns10__GetConfiguration *ns10__GetMetadataConfigurations, _ns10__GetMetadataConfigurationsResponse &ns10__GetMetadataConfigurationsResponse);
        /// Web service operation 'GetAudioOutputConfigurations' (returns SOAP_OK or error code)
        virtual int GetAudioOutputConfigurations(ns10__GetConfiguration *ns10__GetAudioOutputConfigurations, _ns10__GetAudioOutputConfigurationsResponse &ns10__GetAudioOutputConfigurationsResponse)
        { return this->GetAudioOutputConfigurations(NULL, NULL, ns10__GetAudioOutputConfigurations, ns10__GetAudioOutputConfigurationsResponse); }
        virtual int GetAudioOutputConfigurations(const char *soap_endpoint, const char *soap_action, ns10__GetConfiguration *ns10__GetAudioOutputConfigurations, _ns10__GetAudioOutputConfigurationsResponse &ns10__GetAudioOutputConfigurationsResponse);
        /// Web service operation 'GetAudioDecoderConfigurations' (returns SOAP_OK or error code)
        virtual int GetAudioDecoderConfigurations(ns10__GetConfiguration *ns10__GetAudioDecoderConfigurations, _ns10__GetAudioDecoderConfigurationsResponse &ns10__GetAudioDecoderConfigurationsResponse)
        { return this->GetAudioDecoderConfigurations(NULL, NULL, ns10__GetAudioDecoderConfigurations, ns10__GetAudioDecoderConfigurationsResponse); }
        virtual int GetAudioDecoderConfigurations(const char *soap_endpoint, const char *soap_action, ns10__GetConfiguration *ns10__GetAudioDecoderConfigurations, _ns10__GetAudioDecoderConfigurationsResponse &ns10__GetAudioDecoderConfigurationsResponse);
        /// Web service operation 'SetVideoSourceConfiguration' (returns SOAP_OK or error code)
        virtual int SetVideoSourceConfiguration(_ns10__SetVideoSourceConfiguration *ns10__SetVideoSourceConfiguration, _ns10__SetConfigurationResponse &ns10__SetConfigurationResponse)
        { return this->SetVideoSourceConfiguration(NULL, NULL, ns10__SetVideoSourceConfiguration, ns10__SetConfigurationResponse); }
        virtual int SetVideoSourceConfiguration(const char *soap_endpoint, const char *soap_action, _ns10__SetVideoSourceConfiguration *ns10__SetVideoSourceConfiguration, _ns10__SetConfigurationResponse &ns10__SetConfigurationResponse);
        /// Web service operation 'SetVideoEncoderConfiguration' (returns SOAP_OK or error code)
        virtual int SetVideoEncoderConfiguration(_ns10__SetVideoEncoderConfiguration *ns10__SetVideoEncoderConfiguration, _ns10__SetConfigurationResponse &ns10__SetConfigurationResponse)
        { return this->SetVideoEncoderConfiguration(NULL, NULL, ns10__SetVideoEncoderConfiguration, ns10__SetConfigurationResponse); }
        virtual int SetVideoEncoderConfiguration(const char *soap_endpoint, const char *soap_action, _ns10__SetVideoEncoderConfiguration *ns10__SetVideoEncoderConfiguration, _ns10__SetConfigurationResponse &ns10__SetConfigurationResponse);
        /// Web service operation 'SetAudioSourceConfiguration' (returns SOAP_OK or error code)
        virtual int SetAudioSourceConfiguration(_ns10__SetAudioSourceConfiguration *ns10__SetAudioSourceConfiguration, _ns10__SetConfigurationResponse &ns10__SetConfigurationResponse)
        { return this->SetAudioSourceConfiguration(NULL, NULL, ns10__SetAudioSourceConfiguration, ns10__SetConfigurationResponse); }
        virtual int SetAudioSourceConfiguration(const char *soap_endpoint, const char *soap_action, _ns10__SetAudioSourceConfiguration *ns10__SetAudioSourceConfiguration, _ns10__SetConfigurationResponse &ns10__SetConfigurationResponse);
        /// Web service operation 'SetAudioEncoderConfiguration' (returns SOAP_OK or error code)
        virtual int SetAudioEncoderConfiguration(_ns10__SetAudioEncoderConfiguration *ns10__SetAudioEncoderConfiguration, _ns10__SetConfigurationResponse &ns10__SetConfigurationResponse)
        { return this->SetAudioEncoderConfiguration(NULL, NULL, ns10__SetAudioEncoderConfiguration, ns10__SetConfigurationResponse); }
        virtual int SetAudioEncoderConfiguration(const char *soap_endpoint, const char *soap_action, _ns10__SetAudioEncoderConfiguration *ns10__SetAudioEncoderConfiguration, _ns10__SetConfigurationResponse &ns10__SetConfigurationResponse);
        /// Web service operation 'SetMetadataConfiguration' (returns SOAP_OK or error code)
        virtual int SetMetadataConfiguration(_ns10__SetMetadataConfiguration *ns10__SetMetadataConfiguration, _ns10__SetConfigurationResponse &ns10__SetConfigurationResponse)
        { return this->SetMetadataConfiguration(NULL, NULL, ns10__SetMetadataConfiguration, ns10__SetConfigurationResponse); }
        virtual int SetMetadataConfiguration(const char *soap_endpoint, const char *soap_action, _ns10__SetMetadataConfiguration *ns10__SetMetadataConfiguration, _ns10__SetConfigurationResponse &ns10__SetConfigurationResponse);
        /// Web service operation 'SetAudioOutputConfiguration' (returns SOAP_OK or error code)
        virtual int SetAudioOutputConfiguration(_ns10__SetAudioOutputConfiguration *ns10__SetAudioOutputConfiguration, _ns10__SetConfigurationResponse &ns10__SetConfigurationResponse)
        { return this->SetAudioOutputConfiguration(NULL, NULL, ns10__SetAudioOutputConfiguration, ns10__SetConfigurationResponse); }
        virtual int SetAudioOutputConfiguration(const char *soap_endpoint, const char *soap_action, _ns10__SetAudioOutputConfiguration *ns10__SetAudioOutputConfiguration, _ns10__SetConfigurationResponse &ns10__SetConfigurationResponse);
        /// Web service operation 'SetAudioDecoderConfiguration' (returns SOAP_OK or error code)
        virtual int SetAudioDecoderConfiguration(_ns10__SetAudioDecoderConfiguration *ns10__SetAudioDecoderConfiguration, _ns10__SetConfigurationResponse &ns10__SetConfigurationResponse)
        { return this->SetAudioDecoderConfiguration(NULL, NULL, ns10__SetAudioDecoderConfiguration, ns10__SetConfigurationResponse); }
        virtual int SetAudioDecoderConfiguration(const char *soap_endpoint, const char *soap_action, _ns10__SetAudioDecoderConfiguration *ns10__SetAudioDecoderConfiguration, _ns10__SetConfigurationResponse &ns10__SetConfigurationResponse);
        /// Web service operation 'GetVideoSourceConfigurationOptions' (returns SOAP_OK or error code)
        virtual int GetVideoSourceConfigurationOptions(ns10__GetConfiguration *ns10__GetVideoSourceConfigurationOptions, _ns10__GetVideoSourceConfigurationOptionsResponse &ns10__GetVideoSourceConfigurationOptionsResponse)
        { return this->GetVideoSourceConfigurationOptions(NULL, NULL, ns10__GetVideoSourceConfigurationOptions, ns10__GetVideoSourceConfigurationOptionsResponse); }
        virtual int GetVideoSourceConfigurationOptions(const char *soap_endpoint, const char *soap_action, ns10__GetConfiguration *ns10__GetVideoSourceConfigurationOptions, _ns10__GetVideoSourceConfigurationOptionsResponse &ns10__GetVideoSourceConfigurationOptionsResponse);
        /// Web service operation 'GetVideoEncoderConfigurationOptions' (returns SOAP_OK or error code)
        virtual int GetVideoEncoderConfigurationOptions(ns10__GetConfiguration *ns10__GetVideoEncoderConfigurationOptions, _ns10__GetVideoEncoderConfigurationOptionsResponse &ns10__GetVideoEncoderConfigurationOptionsResponse)
        { return this->GetVideoEncoderConfigurationOptions(NULL, NULL, ns10__GetVideoEncoderConfigurationOptions, ns10__GetVideoEncoderConfigurationOptionsResponse); }
        virtual int GetVideoEncoderConfigurationOptions(const char *soap_endpoint, const char *soap_action, ns10__GetConfiguration *ns10__GetVideoEncoderConfigurationOptions, _ns10__GetVideoEncoderConfigurationOptionsResponse &ns10__GetVideoEncoderConfigurationOptionsResponse);
        /// Web service operation 'GetAudioSourceConfigurationOptions' (returns SOAP_OK or error code)
        virtual int GetAudioSourceConfigurationOptions(ns10__GetConfiguration *ns10__GetAudioSourceConfigurationOptions, _ns10__GetAudioSourceConfigurationOptionsResponse &ns10__GetAudioSourceConfigurationOptionsResponse)
        { return this->GetAudioSourceConfigurationOptions(NULL, NULL, ns10__GetAudioSourceConfigurationOptions, ns10__GetAudioSourceConfigurationOptionsResponse); }
        virtual int GetAudioSourceConfigurationOptions(const char *soap_endpoint, const char *soap_action, ns10__GetConfiguration *ns10__GetAudioSourceConfigurationOptions, _ns10__GetAudioSourceConfigurationOptionsResponse &ns10__GetAudioSourceConfigurationOptionsResponse);
        /// Web service operation 'GetAudioEncoderConfigurationOptions' (returns SOAP_OK or error code)
        virtual int GetAudioEncoderConfigurationOptions(ns10__GetConfiguration *ns10__GetAudioEncoderConfigurationOptions, _ns10__GetAudioEncoderConfigurationOptionsResponse &ns10__GetAudioEncoderConfigurationOptionsResponse)
        { return this->GetAudioEncoderConfigurationOptions(NULL, NULL, ns10__GetAudioEncoderConfigurationOptions, ns10__GetAudioEncoderConfigurationOptionsResponse); }
        virtual int GetAudioEncoderConfigurationOptions(const char *soap_endpoint, const char *soap_action, ns10__GetConfiguration *ns10__GetAudioEncoderConfigurationOptions, _ns10__GetAudioEncoderConfigurationOptionsResponse &ns10__GetAudioEncoderConfigurationOptionsResponse);
        /// Web service operation 'GetMetadataConfigurationOptions' (returns SOAP_OK or error code)
        virtual int GetMetadataConfigurationOptions(ns10__GetConfiguration *ns10__GetMetadataConfigurationOptions, _ns10__GetMetadataConfigurationOptionsResponse &ns10__GetMetadataConfigurationOptionsResponse)
        { return this->GetMetadataConfigurationOptions(NULL, NULL, ns10__GetMetadataConfigurationOptions, ns10__GetMetadataConfigurationOptionsResponse); }
        virtual int GetMetadataConfigurationOptions(const char *soap_endpoint, const char *soap_action, ns10__GetConfiguration *ns10__GetMetadataConfigurationOptions, _ns10__GetMetadataConfigurationOptionsResponse &ns10__GetMetadataConfigurationOptionsResponse);
        /// Web service operation 'GetAudioOutputConfigurationOptions' (returns SOAP_OK or error code)
        virtual int GetAudioOutputConfigurationOptions(ns10__GetConfiguration *ns10__GetAudioOutputConfigurationOptions, _ns10__GetAudioOutputConfigurationOptionsResponse &ns10__GetAudioOutputConfigurationOptionsResponse)
        { return this->GetAudioOutputConfigurationOptions(NULL, NULL, ns10__GetAudioOutputConfigurationOptions, ns10__GetAudioOutputConfigurationOptionsResponse); }
        virtual int GetAudioOutputConfigurationOptions(const char *soap_endpoint, const char *soap_action, ns10__GetConfiguration *ns10__GetAudioOutputConfigurationOptions, _ns10__GetAudioOutputConfigurationOptionsResponse &ns10__GetAudioOutputConfigurationOptionsResponse);
        /// Web service operation 'GetAudioDecoderConfigurationOptions' (returns SOAP_OK or error code)
        virtual int GetAudioDecoderConfigurationOptions(ns10__GetConfiguration *ns10__GetAudioDecoderConfigurationOptions, _ns10__GetAudioDecoderConfigurationOptionsResponse &ns10__GetAudioDecoderConfigurationOptionsResponse)
        { return this->GetAudioDecoderConfigurationOptions(NULL, NULL, ns10__GetAudioDecoderConfigurationOptions, ns10__GetAudioDecoderConfigurationOptionsResponse); }
        virtual int GetAudioDecoderConfigurationOptions(const char *soap_endpoint, const char *soap_action, ns10__GetConfiguration *ns10__GetAudioDecoderConfigurationOptions, _ns10__GetAudioDecoderConfigurationOptionsResponse &ns10__GetAudioDecoderConfigurationOptionsResponse);
        /// Web service operation 'GetVideoEncoderInstances' (returns SOAP_OK or error code)
        virtual int GetVideoEncoderInstances(_ns10__GetVideoEncoderInstances *ns10__GetVideoEncoderInstances, _ns10__GetVideoEncoderInstancesResponse &ns10__GetVideoEncoderInstancesResponse)
        { return this->GetVideoEncoderInstances(NULL, NULL, ns10__GetVideoEncoderInstances, ns10__GetVideoEncoderInstancesResponse); }
        virtual int GetVideoEncoderInstances(const char *soap_endpoint, const char *soap_action, _ns10__GetVideoEncoderInstances *ns10__GetVideoEncoderInstances, _ns10__GetVideoEncoderInstancesResponse &ns10__GetVideoEncoderInstancesResponse);
        /// Web service operation 'GetStreamUri' (returns SOAP_OK or error code)
        virtual int GetStreamUri(_ns10__GetStreamUri *ns10__GetStreamUri, _ns10__GetStreamUriResponse &ns10__GetStreamUriResponse)
        { return this->GetStreamUri(NULL, NULL, ns10__GetStreamUri, ns10__GetStreamUriResponse); }
        virtual int GetStreamUri(const char *soap_endpoint, const char *soap_action, _ns10__GetStreamUri *ns10__GetStreamUri, _ns10__GetStreamUriResponse &ns10__GetStreamUriResponse);
        /// Web service operation 'StartMulticastStreaming' (returns SOAP_OK or error code)
        virtual int StartMulticastStreaming(ns10__StartStopMulticastStreaming *ns10__StartMulticastStreaming, _ns10__StartStopMulticastStreamingResponse &ns10__StartStopMulticastStreamingResponse)
        { return this->StartMulticastStreaming(NULL, NULL, ns10__StartMulticastStreaming, ns10__StartStopMulticastStreamingResponse); }
        virtual int StartMulticastStreaming(const char *soap_endpoint, const char *soap_action, ns10__StartStopMulticastStreaming *ns10__StartMulticastStreaming, _ns10__StartStopMulticastStreamingResponse &ns10__StartStopMulticastStreamingResponse);
        /// Web service operation 'StopMulticastStreaming' (returns SOAP_OK or error code)
        virtual int StopMulticastStreaming(ns10__StartStopMulticastStreaming *ns10__StopMulticastStreaming, _ns10__StartStopMulticastStreamingResponse &ns10__StartStopMulticastStreamingResponse)
        { return this->StopMulticastStreaming(NULL, NULL, ns10__StopMulticastStreaming, ns10__StartStopMulticastStreamingResponse); }
        virtual int StopMulticastStreaming(const char *soap_endpoint, const char *soap_action, ns10__StartStopMulticastStreaming *ns10__StopMulticastStreaming, _ns10__StartStopMulticastStreamingResponse &ns10__StartStopMulticastStreamingResponse);
        /// Web service operation 'SetSynchronizationPoint' (returns SOAP_OK or error code)
        virtual int SetSynchronizationPoint(_ns10__SetSynchronizationPoint *ns10__SetSynchronizationPoint, _ns10__SetSynchronizationPointResponse &ns10__SetSynchronizationPointResponse)
        { return this->SetSynchronizationPoint(NULL, NULL, ns10__SetSynchronizationPoint, ns10__SetSynchronizationPointResponse); }
        virtual int SetSynchronizationPoint(const char *soap_endpoint, const char *soap_action, _ns10__SetSynchronizationPoint *ns10__SetSynchronizationPoint, _ns10__SetSynchronizationPointResponse &ns10__SetSynchronizationPointResponse);
        /// Web service operation 'GetSnapshotUri' (returns SOAP_OK or error code)
        virtual int GetSnapshotUri(_ns10__GetSnapshotUri *ns10__GetSnapshotUri, _ns10__GetSnapshotUriResponse &ns10__GetSnapshotUriResponse)
        { return this->GetSnapshotUri(NULL, NULL, ns10__GetSnapshotUri, ns10__GetSnapshotUriResponse); }
        virtual int GetSnapshotUri(const char *soap_endpoint, const char *soap_action, _ns10__GetSnapshotUri *ns10__GetSnapshotUri, _ns10__GetSnapshotUriResponse &ns10__GetSnapshotUriResponse);
        /// Web service operation 'GetVideoSourceModes' (returns SOAP_OK or error code)
        virtual int GetVideoSourceModes(_ns10__GetVideoSourceModes *ns10__GetVideoSourceModes, _ns10__GetVideoSourceModesResponse &ns10__GetVideoSourceModesResponse)
        { return this->GetVideoSourceModes(NULL, NULL, ns10__GetVideoSourceModes, ns10__GetVideoSourceModesResponse); }
        virtual int GetVideoSourceModes(const char *soap_endpoint, const char *soap_action, _ns10__GetVideoSourceModes *ns10__GetVideoSourceModes, _ns10__GetVideoSourceModesResponse &ns10__GetVideoSourceModesResponse);
        /// Web service operation 'SetVideoSourceMode' (returns SOAP_OK or error code)
        virtual int SetVideoSourceMode(_ns10__SetVideoSourceMode *ns10__SetVideoSourceMode, _ns10__SetVideoSourceModeResponse &ns10__SetVideoSourceModeResponse)
        { return this->SetVideoSourceMode(NULL, NULL, ns10__SetVideoSourceMode, ns10__SetVideoSourceModeResponse); }
        virtual int SetVideoSourceMode(const char *soap_endpoint, const char *soap_action, _ns10__SetVideoSourceMode *ns10__SetVideoSourceMode, _ns10__SetVideoSourceModeResponse &ns10__SetVideoSourceModeResponse);
        /// Web service operation 'GetOSDs' (returns SOAP_OK or error code)
        virtual int GetOSDs(_ns10__GetOSDs *ns10__GetOSDs, _ns10__GetOSDsResponse &ns10__GetOSDsResponse)
        { return this->GetOSDs(NULL, NULL, ns10__GetOSDs, ns10__GetOSDsResponse); }
        virtual int GetOSDs(const char *soap_endpoint, const char *soap_action, _ns10__GetOSDs *ns10__GetOSDs, _ns10__GetOSDsResponse &ns10__GetOSDsResponse);
        /// Web service operation 'GetOSDOptions' (returns SOAP_OK or error code)
        virtual int GetOSDOptions(_ns10__GetOSDOptions *ns10__GetOSDOptions, _ns10__GetOSDOptionsResponse &ns10__GetOSDOptionsResponse)
        { return this->GetOSDOptions(NULL, NULL, ns10__GetOSDOptions, ns10__GetOSDOptionsResponse); }
        virtual int GetOSDOptions(const char *soap_endpoint, const char *soap_action, _ns10__GetOSDOptions *ns10__GetOSDOptions, _ns10__GetOSDOptionsResponse &ns10__GetOSDOptionsResponse);
        /// Web service operation 'SetOSD' (returns SOAP_OK or error code)
        virtual int SetOSD(_ns10__SetOSD *ns10__SetOSD, _ns10__SetConfigurationResponse &ns10__SetConfigurationResponse)
        { return this->SetOSD(NULL, NULL, ns10__SetOSD, ns10__SetConfigurationResponse); }
        virtual int SetOSD(const char *soap_endpoint, const char *soap_action, _ns10__SetOSD *ns10__SetOSD, _ns10__SetConfigurationResponse &ns10__SetConfigurationResponse);
        /// Web service operation 'CreateOSD' (returns SOAP_OK or error code)
        virtual int CreateOSD(_ns10__CreateOSD *ns10__CreateOSD, _ns10__CreateOSDResponse &ns10__CreateOSDResponse)
        { return this->CreateOSD(NULL, NULL, ns10__CreateOSD, ns10__CreateOSDResponse); }
        virtual int CreateOSD(const char *soap_endpoint, const char *soap_action, _ns10__CreateOSD *ns10__CreateOSD, _ns10__CreateOSDResponse &ns10__CreateOSDResponse);
        /// Web service operation 'DeleteOSD' (returns SOAP_OK or error code)
        virtual int DeleteOSD(_ns10__DeleteOSD *ns10__DeleteOSD, _ns10__SetConfigurationResponse &ns10__SetConfigurationResponse)
        { return this->DeleteOSD(NULL, NULL, ns10__DeleteOSD, ns10__SetConfigurationResponse); }
        virtual int DeleteOSD(const char *soap_endpoint, const char *soap_action, _ns10__DeleteOSD *ns10__DeleteOSD, _ns10__SetConfigurationResponse &ns10__SetConfigurationResponse);
    };
#endif
