/* soapDeviceBindingProxy.h
   Generated by gSOAP 2.8.40 for onvifgen/onvif.h

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapDeviceBindingProxy_H
#define soapDeviceBindingProxy_H
#include "soapH.h"

    class SOAP_CMAC DeviceBindingProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        bool soap_own; ///< flag indicating that this context is owned by this proxy when context is shared
        /// Endpoint URL of service 'DeviceBindingProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in onvifgen/onvif.h, if any
        /// Construct a proxy with new managing context
        DeviceBindingProxy();
        /// Copy constructor
        DeviceBindingProxy(const DeviceBindingProxy& rhs);
        /// Construct proxy given a shared managing context
        DeviceBindingProxy(struct soap*);
        /// Constructor taking an endpoint URL
        DeviceBindingProxy(const char *endpoint);
        /// Constructor taking input and output mode flags for the new managing context
        DeviceBindingProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        DeviceBindingProxy(const char *endpoint, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        DeviceBindingProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes non-shared managing context only (use destroy() to delete deserialized data)
        virtual ~DeviceBindingProxy();
        /// Initializer used by constructors
        virtual void DeviceBindingProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual DeviceBindingProxy *copy() SOAP_PURE_VIRTUAL;
        /// Copy assignment
        DeviceBindingProxy& operator=(const DeviceBindingProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Add SOAP Header to message
        virtual void soap_header(struct _wsse__Security *wsse__Security);
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault string (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail as string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Web service operation 'GetServices' (returns SOAP_OK or error code)
        virtual int GetServices(_ns1__GetServices *ns1__GetServices, _ns1__GetServicesResponse &ns1__GetServicesResponse)
        { return this->GetServices(NULL, NULL, ns1__GetServices, ns1__GetServicesResponse); }
        virtual int GetServices(const char *soap_endpoint, const char *soap_action, _ns1__GetServices *ns1__GetServices, _ns1__GetServicesResponse &ns1__GetServicesResponse);
        /// Web service operation 'GetServiceCapabilities' (returns SOAP_OK or error code)
        virtual int GetServiceCapabilities(_ns1__GetServiceCapabilities *ns1__GetServiceCapabilities, _ns1__GetServiceCapabilitiesResponse &ns1__GetServiceCapabilitiesResponse)
        { return this->GetServiceCapabilities(NULL, NULL, ns1__GetServiceCapabilities, ns1__GetServiceCapabilitiesResponse); }
        virtual int GetServiceCapabilities(const char *soap_endpoint, const char *soap_action, _ns1__GetServiceCapabilities *ns1__GetServiceCapabilities, _ns1__GetServiceCapabilitiesResponse &ns1__GetServiceCapabilitiesResponse);
        /// Web service operation 'GetDeviceInformation' (returns SOAP_OK or error code)
        virtual int GetDeviceInformation(_ns1__GetDeviceInformation *ns1__GetDeviceInformation, _ns1__GetDeviceInformationResponse &ns1__GetDeviceInformationResponse)
        { return this->GetDeviceInformation(NULL, NULL, ns1__GetDeviceInformation, ns1__GetDeviceInformationResponse); }
        virtual int GetDeviceInformation(const char *soap_endpoint, const char *soap_action, _ns1__GetDeviceInformation *ns1__GetDeviceInformation, _ns1__GetDeviceInformationResponse &ns1__GetDeviceInformationResponse);
        /// Web service operation 'SetSystemDateAndTime' (returns SOAP_OK or error code)
        virtual int SetSystemDateAndTime(_ns1__SetSystemDateAndTime *ns1__SetSystemDateAndTime, _ns1__SetSystemDateAndTimeResponse &ns1__SetSystemDateAndTimeResponse)
        { return this->SetSystemDateAndTime(NULL, NULL, ns1__SetSystemDateAndTime, ns1__SetSystemDateAndTimeResponse); }
        virtual int SetSystemDateAndTime(const char *soap_endpoint, const char *soap_action, _ns1__SetSystemDateAndTime *ns1__SetSystemDateAndTime, _ns1__SetSystemDateAndTimeResponse &ns1__SetSystemDateAndTimeResponse);
        /// Web service operation 'GetSystemDateAndTime' (returns SOAP_OK or error code)
        virtual int GetSystemDateAndTime(_ns1__GetSystemDateAndTime *ns1__GetSystemDateAndTime, _ns1__GetSystemDateAndTimeResponse &ns1__GetSystemDateAndTimeResponse)
        { return this->GetSystemDateAndTime(NULL, NULL, ns1__GetSystemDateAndTime, ns1__GetSystemDateAndTimeResponse); }
        virtual int GetSystemDateAndTime(const char *soap_endpoint, const char *soap_action, _ns1__GetSystemDateAndTime *ns1__GetSystemDateAndTime, _ns1__GetSystemDateAndTimeResponse &ns1__GetSystemDateAndTimeResponse);
        /// Web service operation 'SetSystemFactoryDefault' (returns SOAP_OK or error code)
        virtual int SetSystemFactoryDefault(_ns1__SetSystemFactoryDefault *ns1__SetSystemFactoryDefault, _ns1__SetSystemFactoryDefaultResponse &ns1__SetSystemFactoryDefaultResponse)
        { return this->SetSystemFactoryDefault(NULL, NULL, ns1__SetSystemFactoryDefault, ns1__SetSystemFactoryDefaultResponse); }
        virtual int SetSystemFactoryDefault(const char *soap_endpoint, const char *soap_action, _ns1__SetSystemFactoryDefault *ns1__SetSystemFactoryDefault, _ns1__SetSystemFactoryDefaultResponse &ns1__SetSystemFactoryDefaultResponse);
        /// Web service operation 'UpgradeSystemFirmware' (returns SOAP_OK or error code)
        virtual int UpgradeSystemFirmware(_ns1__UpgradeSystemFirmware *ns1__UpgradeSystemFirmware, _ns1__UpgradeSystemFirmwareResponse &ns1__UpgradeSystemFirmwareResponse)
        { return this->UpgradeSystemFirmware(NULL, NULL, ns1__UpgradeSystemFirmware, ns1__UpgradeSystemFirmwareResponse); }
        virtual int UpgradeSystemFirmware(const char *soap_endpoint, const char *soap_action, _ns1__UpgradeSystemFirmware *ns1__UpgradeSystemFirmware, _ns1__UpgradeSystemFirmwareResponse &ns1__UpgradeSystemFirmwareResponse);
        /// Web service operation 'SystemReboot' (returns SOAP_OK or error code)
        virtual int SystemReboot(_ns1__SystemReboot *ns1__SystemReboot, _ns1__SystemRebootResponse &ns1__SystemRebootResponse)
        { return this->SystemReboot(NULL, NULL, ns1__SystemReboot, ns1__SystemRebootResponse); }
        virtual int SystemReboot(const char *soap_endpoint, const char *soap_action, _ns1__SystemReboot *ns1__SystemReboot, _ns1__SystemRebootResponse &ns1__SystemRebootResponse);
        /// Web service operation 'RestoreSystem' (returns SOAP_OK or error code)
        virtual int RestoreSystem(_ns1__RestoreSystem *ns1__RestoreSystem, _ns1__RestoreSystemResponse &ns1__RestoreSystemResponse)
        { return this->RestoreSystem(NULL, NULL, ns1__RestoreSystem, ns1__RestoreSystemResponse); }
        virtual int RestoreSystem(const char *soap_endpoint, const char *soap_action, _ns1__RestoreSystem *ns1__RestoreSystem, _ns1__RestoreSystemResponse &ns1__RestoreSystemResponse);
        /// Web service operation 'GetSystemBackup' (returns SOAP_OK or error code)
        virtual int GetSystemBackup(_ns1__GetSystemBackup *ns1__GetSystemBackup, _ns1__GetSystemBackupResponse &ns1__GetSystemBackupResponse)
        { return this->GetSystemBackup(NULL, NULL, ns1__GetSystemBackup, ns1__GetSystemBackupResponse); }
        virtual int GetSystemBackup(const char *soap_endpoint, const char *soap_action, _ns1__GetSystemBackup *ns1__GetSystemBackup, _ns1__GetSystemBackupResponse &ns1__GetSystemBackupResponse);
        /// Web service operation 'GetSystemLog' (returns SOAP_OK or error code)
        virtual int GetSystemLog(_ns1__GetSystemLog *ns1__GetSystemLog, _ns1__GetSystemLogResponse &ns1__GetSystemLogResponse)
        { return this->GetSystemLog(NULL, NULL, ns1__GetSystemLog, ns1__GetSystemLogResponse); }
        virtual int GetSystemLog(const char *soap_endpoint, const char *soap_action, _ns1__GetSystemLog *ns1__GetSystemLog, _ns1__GetSystemLogResponse &ns1__GetSystemLogResponse);
        /// Web service operation 'GetSystemSupportInformation' (returns SOAP_OK or error code)
        virtual int GetSystemSupportInformation(_ns1__GetSystemSupportInformation *ns1__GetSystemSupportInformation, _ns1__GetSystemSupportInformationResponse &ns1__GetSystemSupportInformationResponse)
        { return this->GetSystemSupportInformation(NULL, NULL, ns1__GetSystemSupportInformation, ns1__GetSystemSupportInformationResponse); }
        virtual int GetSystemSupportInformation(const char *soap_endpoint, const char *soap_action, _ns1__GetSystemSupportInformation *ns1__GetSystemSupportInformation, _ns1__GetSystemSupportInformationResponse &ns1__GetSystemSupportInformationResponse);
        /// Web service operation 'GetScopes' (returns SOAP_OK or error code)
        virtual int GetScopes(_ns1__GetScopes *ns1__GetScopes, _ns1__GetScopesResponse &ns1__GetScopesResponse)
        { return this->GetScopes(NULL, NULL, ns1__GetScopes, ns1__GetScopesResponse); }
        virtual int GetScopes(const char *soap_endpoint, const char *soap_action, _ns1__GetScopes *ns1__GetScopes, _ns1__GetScopesResponse &ns1__GetScopesResponse);
        /// Web service operation 'SetScopes' (returns SOAP_OK or error code)
        virtual int SetScopes(_ns1__SetScopes *ns1__SetScopes, _ns1__SetScopesResponse &ns1__SetScopesResponse)
        { return this->SetScopes(NULL, NULL, ns1__SetScopes, ns1__SetScopesResponse); }
        virtual int SetScopes(const char *soap_endpoint, const char *soap_action, _ns1__SetScopes *ns1__SetScopes, _ns1__SetScopesResponse &ns1__SetScopesResponse);
        /// Web service operation 'AddScopes' (returns SOAP_OK or error code)
        virtual int AddScopes(_ns1__AddScopes *ns1__AddScopes, _ns1__AddScopesResponse &ns1__AddScopesResponse)
        { return this->AddScopes(NULL, NULL, ns1__AddScopes, ns1__AddScopesResponse); }
        virtual int AddScopes(const char *soap_endpoint, const char *soap_action, _ns1__AddScopes *ns1__AddScopes, _ns1__AddScopesResponse &ns1__AddScopesResponse);
        /// Web service operation 'RemoveScopes' (returns SOAP_OK or error code)
        virtual int RemoveScopes(_ns1__RemoveScopes *ns1__RemoveScopes, _ns1__RemoveScopesResponse &ns1__RemoveScopesResponse)
        { return this->RemoveScopes(NULL, NULL, ns1__RemoveScopes, ns1__RemoveScopesResponse); }
        virtual int RemoveScopes(const char *soap_endpoint, const char *soap_action, _ns1__RemoveScopes *ns1__RemoveScopes, _ns1__RemoveScopesResponse &ns1__RemoveScopesResponse);
        /// Web service operation 'GetDiscoveryMode' (returns SOAP_OK or error code)
        virtual int GetDiscoveryMode(_ns1__GetDiscoveryMode *ns1__GetDiscoveryMode, _ns1__GetDiscoveryModeResponse &ns1__GetDiscoveryModeResponse)
        { return this->GetDiscoveryMode(NULL, NULL, ns1__GetDiscoveryMode, ns1__GetDiscoveryModeResponse); }
        virtual int GetDiscoveryMode(const char *soap_endpoint, const char *soap_action, _ns1__GetDiscoveryMode *ns1__GetDiscoveryMode, _ns1__GetDiscoveryModeResponse &ns1__GetDiscoveryModeResponse);
        /// Web service operation 'SetDiscoveryMode' (returns SOAP_OK or error code)
        virtual int SetDiscoveryMode(_ns1__SetDiscoveryMode *ns1__SetDiscoveryMode, _ns1__SetDiscoveryModeResponse &ns1__SetDiscoveryModeResponse)
        { return this->SetDiscoveryMode(NULL, NULL, ns1__SetDiscoveryMode, ns1__SetDiscoveryModeResponse); }
        virtual int SetDiscoveryMode(const char *soap_endpoint, const char *soap_action, _ns1__SetDiscoveryMode *ns1__SetDiscoveryMode, _ns1__SetDiscoveryModeResponse &ns1__SetDiscoveryModeResponse);
        /// Web service operation 'GetRemoteDiscoveryMode' (returns SOAP_OK or error code)
        virtual int GetRemoteDiscoveryMode(_ns1__GetRemoteDiscoveryMode *ns1__GetRemoteDiscoveryMode, _ns1__GetRemoteDiscoveryModeResponse &ns1__GetRemoteDiscoveryModeResponse)
        { return this->GetRemoteDiscoveryMode(NULL, NULL, ns1__GetRemoteDiscoveryMode, ns1__GetRemoteDiscoveryModeResponse); }
        virtual int GetRemoteDiscoveryMode(const char *soap_endpoint, const char *soap_action, _ns1__GetRemoteDiscoveryMode *ns1__GetRemoteDiscoveryMode, _ns1__GetRemoteDiscoveryModeResponse &ns1__GetRemoteDiscoveryModeResponse);
        /// Web service operation 'SetRemoteDiscoveryMode' (returns SOAP_OK or error code)
        virtual int SetRemoteDiscoveryMode(_ns1__SetRemoteDiscoveryMode *ns1__SetRemoteDiscoveryMode, _ns1__SetRemoteDiscoveryModeResponse &ns1__SetRemoteDiscoveryModeResponse)
        { return this->SetRemoteDiscoveryMode(NULL, NULL, ns1__SetRemoteDiscoveryMode, ns1__SetRemoteDiscoveryModeResponse); }
        virtual int SetRemoteDiscoveryMode(const char *soap_endpoint, const char *soap_action, _ns1__SetRemoteDiscoveryMode *ns1__SetRemoteDiscoveryMode, _ns1__SetRemoteDiscoveryModeResponse &ns1__SetRemoteDiscoveryModeResponse);
        /// Web service operation 'GetDPAddresses' (returns SOAP_OK or error code)
        virtual int GetDPAddresses(_ns1__GetDPAddresses *ns1__GetDPAddresses, _ns1__GetDPAddressesResponse &ns1__GetDPAddressesResponse)
        { return this->GetDPAddresses(NULL, NULL, ns1__GetDPAddresses, ns1__GetDPAddressesResponse); }
        virtual int GetDPAddresses(const char *soap_endpoint, const char *soap_action, _ns1__GetDPAddresses *ns1__GetDPAddresses, _ns1__GetDPAddressesResponse &ns1__GetDPAddressesResponse);
        /// Web service operation 'GetEndpointReference' (returns SOAP_OK or error code)
        virtual int GetEndpointReference(_ns1__GetEndpointReference *ns1__GetEndpointReference, _ns1__GetEndpointReferenceResponse &ns1__GetEndpointReferenceResponse)
        { return this->GetEndpointReference(NULL, NULL, ns1__GetEndpointReference, ns1__GetEndpointReferenceResponse); }
        virtual int GetEndpointReference(const char *soap_endpoint, const char *soap_action, _ns1__GetEndpointReference *ns1__GetEndpointReference, _ns1__GetEndpointReferenceResponse &ns1__GetEndpointReferenceResponse);
        /// Web service operation 'GetRemoteUser' (returns SOAP_OK or error code)
        virtual int GetRemoteUser(_ns1__GetRemoteUser *ns1__GetRemoteUser, _ns1__GetRemoteUserResponse &ns1__GetRemoteUserResponse)
        { return this->GetRemoteUser(NULL, NULL, ns1__GetRemoteUser, ns1__GetRemoteUserResponse); }
        virtual int GetRemoteUser(const char *soap_endpoint, const char *soap_action, _ns1__GetRemoteUser *ns1__GetRemoteUser, _ns1__GetRemoteUserResponse &ns1__GetRemoteUserResponse);
        /// Web service operation 'SetRemoteUser' (returns SOAP_OK or error code)
        virtual int SetRemoteUser(_ns1__SetRemoteUser *ns1__SetRemoteUser, _ns1__SetRemoteUserResponse &ns1__SetRemoteUserResponse)
        { return this->SetRemoteUser(NULL, NULL, ns1__SetRemoteUser, ns1__SetRemoteUserResponse); }
        virtual int SetRemoteUser(const char *soap_endpoint, const char *soap_action, _ns1__SetRemoteUser *ns1__SetRemoteUser, _ns1__SetRemoteUserResponse &ns1__SetRemoteUserResponse);
        /// Web service operation 'GetUsers' (returns SOAP_OK or error code)
        virtual int GetUsers(_ns1__GetUsers *ns1__GetUsers, _ns1__GetUsersResponse &ns1__GetUsersResponse)
        { return this->GetUsers(NULL, NULL, ns1__GetUsers, ns1__GetUsersResponse); }
        virtual int GetUsers(const char *soap_endpoint, const char *soap_action, _ns1__GetUsers *ns1__GetUsers, _ns1__GetUsersResponse &ns1__GetUsersResponse);
        /// Web service operation 'CreateUsers' (returns SOAP_OK or error code)
        virtual int CreateUsers(_ns1__CreateUsers *ns1__CreateUsers, _ns1__CreateUsersResponse &ns1__CreateUsersResponse)
        { return this->CreateUsers(NULL, NULL, ns1__CreateUsers, ns1__CreateUsersResponse); }
        virtual int CreateUsers(const char *soap_endpoint, const char *soap_action, _ns1__CreateUsers *ns1__CreateUsers, _ns1__CreateUsersResponse &ns1__CreateUsersResponse);
        /// Web service operation 'DeleteUsers' (returns SOAP_OK or error code)
        virtual int DeleteUsers(_ns1__DeleteUsers *ns1__DeleteUsers, _ns1__DeleteUsersResponse &ns1__DeleteUsersResponse)
        { return this->DeleteUsers(NULL, NULL, ns1__DeleteUsers, ns1__DeleteUsersResponse); }
        virtual int DeleteUsers(const char *soap_endpoint, const char *soap_action, _ns1__DeleteUsers *ns1__DeleteUsers, _ns1__DeleteUsersResponse &ns1__DeleteUsersResponse);
        /// Web service operation 'SetUser' (returns SOAP_OK or error code)
        virtual int SetUser(_ns1__SetUser *ns1__SetUser, _ns1__SetUserResponse &ns1__SetUserResponse)
        { return this->SetUser(NULL, NULL, ns1__SetUser, ns1__SetUserResponse); }
        virtual int SetUser(const char *soap_endpoint, const char *soap_action, _ns1__SetUser *ns1__SetUser, _ns1__SetUserResponse &ns1__SetUserResponse);
        /// Web service operation 'GetWsdlUrl' (returns SOAP_OK or error code)
        virtual int GetWsdlUrl(_ns1__GetWsdlUrl *ns1__GetWsdlUrl, _ns1__GetWsdlUrlResponse &ns1__GetWsdlUrlResponse)
        { return this->GetWsdlUrl(NULL, NULL, ns1__GetWsdlUrl, ns1__GetWsdlUrlResponse); }
        virtual int GetWsdlUrl(const char *soap_endpoint, const char *soap_action, _ns1__GetWsdlUrl *ns1__GetWsdlUrl, _ns1__GetWsdlUrlResponse &ns1__GetWsdlUrlResponse);
        /// Web service operation 'GetCapabilities' (returns SOAP_OK or error code)
        virtual int GetCapabilities(_ns1__GetCapabilities *ns1__GetCapabilities, _ns1__GetCapabilitiesResponse &ns1__GetCapabilitiesResponse)
        { return this->GetCapabilities(NULL, NULL, ns1__GetCapabilities, ns1__GetCapabilitiesResponse); }
        virtual int GetCapabilities(const char *soap_endpoint, const char *soap_action, _ns1__GetCapabilities *ns1__GetCapabilities, _ns1__GetCapabilitiesResponse &ns1__GetCapabilitiesResponse);
        /// Web service operation 'SetDPAddresses' (returns SOAP_OK or error code)
        virtual int SetDPAddresses(_ns1__SetDPAddresses *ns1__SetDPAddresses, _ns1__SetDPAddressesResponse &ns1__SetDPAddressesResponse)
        { return this->SetDPAddresses(NULL, NULL, ns1__SetDPAddresses, ns1__SetDPAddressesResponse); }
        virtual int SetDPAddresses(const char *soap_endpoint, const char *soap_action, _ns1__SetDPAddresses *ns1__SetDPAddresses, _ns1__SetDPAddressesResponse &ns1__SetDPAddressesResponse);
        /// Web service operation 'GetHostname' (returns SOAP_OK or error code)
        virtual int GetHostname(_ns1__GetHostname *ns1__GetHostname, _ns1__GetHostnameResponse &ns1__GetHostnameResponse)
        { return this->GetHostname(NULL, NULL, ns1__GetHostname, ns1__GetHostnameResponse); }
        virtual int GetHostname(const char *soap_endpoint, const char *soap_action, _ns1__GetHostname *ns1__GetHostname, _ns1__GetHostnameResponse &ns1__GetHostnameResponse);
        /// Web service operation 'SetHostname' (returns SOAP_OK or error code)
        virtual int SetHostname(_ns1__SetHostname *ns1__SetHostname, _ns1__SetHostnameResponse &ns1__SetHostnameResponse)
        { return this->SetHostname(NULL, NULL, ns1__SetHostname, ns1__SetHostnameResponse); }
        virtual int SetHostname(const char *soap_endpoint, const char *soap_action, _ns1__SetHostname *ns1__SetHostname, _ns1__SetHostnameResponse &ns1__SetHostnameResponse);
        /// Web service operation 'SetHostnameFromDHCP' (returns SOAP_OK or error code)
        virtual int SetHostnameFromDHCP(_ns1__SetHostnameFromDHCP *ns1__SetHostnameFromDHCP, _ns1__SetHostnameFromDHCPResponse &ns1__SetHostnameFromDHCPResponse)
        { return this->SetHostnameFromDHCP(NULL, NULL, ns1__SetHostnameFromDHCP, ns1__SetHostnameFromDHCPResponse); }
        virtual int SetHostnameFromDHCP(const char *soap_endpoint, const char *soap_action, _ns1__SetHostnameFromDHCP *ns1__SetHostnameFromDHCP, _ns1__SetHostnameFromDHCPResponse &ns1__SetHostnameFromDHCPResponse);
        /// Web service operation 'GetDNS' (returns SOAP_OK or error code)
        virtual int GetDNS(_ns1__GetDNS *ns1__GetDNS, _ns1__GetDNSResponse &ns1__GetDNSResponse)
        { return this->GetDNS(NULL, NULL, ns1__GetDNS, ns1__GetDNSResponse); }
        virtual int GetDNS(const char *soap_endpoint, const char *soap_action, _ns1__GetDNS *ns1__GetDNS, _ns1__GetDNSResponse &ns1__GetDNSResponse);
        /// Web service operation 'SetDNS' (returns SOAP_OK or error code)
        virtual int SetDNS(_ns1__SetDNS *ns1__SetDNS, _ns1__SetDNSResponse &ns1__SetDNSResponse)
        { return this->SetDNS(NULL, NULL, ns1__SetDNS, ns1__SetDNSResponse); }
        virtual int SetDNS(const char *soap_endpoint, const char *soap_action, _ns1__SetDNS *ns1__SetDNS, _ns1__SetDNSResponse &ns1__SetDNSResponse);
        /// Web service operation 'GetNTP' (returns SOAP_OK or error code)
        virtual int GetNTP(_ns1__GetNTP *ns1__GetNTP, _ns1__GetNTPResponse &ns1__GetNTPResponse)
        { return this->GetNTP(NULL, NULL, ns1__GetNTP, ns1__GetNTPResponse); }
        virtual int GetNTP(const char *soap_endpoint, const char *soap_action, _ns1__GetNTP *ns1__GetNTP, _ns1__GetNTPResponse &ns1__GetNTPResponse);
        /// Web service operation 'SetNTP' (returns SOAP_OK or error code)
        virtual int SetNTP(_ns1__SetNTP *ns1__SetNTP, _ns1__SetNTPResponse &ns1__SetNTPResponse)
        { return this->SetNTP(NULL, NULL, ns1__SetNTP, ns1__SetNTPResponse); }
        virtual int SetNTP(const char *soap_endpoint, const char *soap_action, _ns1__SetNTP *ns1__SetNTP, _ns1__SetNTPResponse &ns1__SetNTPResponse);
        /// Web service operation 'GetDynamicDNS' (returns SOAP_OK or error code)
        virtual int GetDynamicDNS(_ns1__GetDynamicDNS *ns1__GetDynamicDNS, _ns1__GetDynamicDNSResponse &ns1__GetDynamicDNSResponse)
        { return this->GetDynamicDNS(NULL, NULL, ns1__GetDynamicDNS, ns1__GetDynamicDNSResponse); }
        virtual int GetDynamicDNS(const char *soap_endpoint, const char *soap_action, _ns1__GetDynamicDNS *ns1__GetDynamicDNS, _ns1__GetDynamicDNSResponse &ns1__GetDynamicDNSResponse);
        /// Web service operation 'SetDynamicDNS' (returns SOAP_OK or error code)
        virtual int SetDynamicDNS(_ns1__SetDynamicDNS *ns1__SetDynamicDNS, _ns1__SetDynamicDNSResponse &ns1__SetDynamicDNSResponse)
        { return this->SetDynamicDNS(NULL, NULL, ns1__SetDynamicDNS, ns1__SetDynamicDNSResponse); }
        virtual int SetDynamicDNS(const char *soap_endpoint, const char *soap_action, _ns1__SetDynamicDNS *ns1__SetDynamicDNS, _ns1__SetDynamicDNSResponse &ns1__SetDynamicDNSResponse);
        /// Web service operation 'GetNetworkInterfaces' (returns SOAP_OK or error code)
        virtual int GetNetworkInterfaces(_ns1__GetNetworkInterfaces *ns1__GetNetworkInterfaces, _ns1__GetNetworkInterfacesResponse &ns1__GetNetworkInterfacesResponse)
        { return this->GetNetworkInterfaces(NULL, NULL, ns1__GetNetworkInterfaces, ns1__GetNetworkInterfacesResponse); }
        virtual int GetNetworkInterfaces(const char *soap_endpoint, const char *soap_action, _ns1__GetNetworkInterfaces *ns1__GetNetworkInterfaces, _ns1__GetNetworkInterfacesResponse &ns1__GetNetworkInterfacesResponse);
        /// Web service operation 'SetNetworkInterfaces' (returns SOAP_OK or error code)
        virtual int SetNetworkInterfaces(_ns1__SetNetworkInterfaces *ns1__SetNetworkInterfaces, _ns1__SetNetworkInterfacesResponse &ns1__SetNetworkInterfacesResponse)
        { return this->SetNetworkInterfaces(NULL, NULL, ns1__SetNetworkInterfaces, ns1__SetNetworkInterfacesResponse); }
        virtual int SetNetworkInterfaces(const char *soap_endpoint, const char *soap_action, _ns1__SetNetworkInterfaces *ns1__SetNetworkInterfaces, _ns1__SetNetworkInterfacesResponse &ns1__SetNetworkInterfacesResponse);
        /// Web service operation 'GetNetworkProtocols' (returns SOAP_OK or error code)
        virtual int GetNetworkProtocols(_ns1__GetNetworkProtocols *ns1__GetNetworkProtocols, _ns1__GetNetworkProtocolsResponse &ns1__GetNetworkProtocolsResponse)
        { return this->GetNetworkProtocols(NULL, NULL, ns1__GetNetworkProtocols, ns1__GetNetworkProtocolsResponse); }
        virtual int GetNetworkProtocols(const char *soap_endpoint, const char *soap_action, _ns1__GetNetworkProtocols *ns1__GetNetworkProtocols, _ns1__GetNetworkProtocolsResponse &ns1__GetNetworkProtocolsResponse);
        /// Web service operation 'SetNetworkProtocols' (returns SOAP_OK or error code)
        virtual int SetNetworkProtocols(_ns1__SetNetworkProtocols *ns1__SetNetworkProtocols, _ns1__SetNetworkProtocolsResponse &ns1__SetNetworkProtocolsResponse)
        { return this->SetNetworkProtocols(NULL, NULL, ns1__SetNetworkProtocols, ns1__SetNetworkProtocolsResponse); }
        virtual int SetNetworkProtocols(const char *soap_endpoint, const char *soap_action, _ns1__SetNetworkProtocols *ns1__SetNetworkProtocols, _ns1__SetNetworkProtocolsResponse &ns1__SetNetworkProtocolsResponse);
        /// Web service operation 'GetNetworkDefaultGateway' (returns SOAP_OK or error code)
        virtual int GetNetworkDefaultGateway(_ns1__GetNetworkDefaultGateway *ns1__GetNetworkDefaultGateway, _ns1__GetNetworkDefaultGatewayResponse &ns1__GetNetworkDefaultGatewayResponse)
        { return this->GetNetworkDefaultGateway(NULL, NULL, ns1__GetNetworkDefaultGateway, ns1__GetNetworkDefaultGatewayResponse); }
        virtual int GetNetworkDefaultGateway(const char *soap_endpoint, const char *soap_action, _ns1__GetNetworkDefaultGateway *ns1__GetNetworkDefaultGateway, _ns1__GetNetworkDefaultGatewayResponse &ns1__GetNetworkDefaultGatewayResponse);
        /// Web service operation 'SetNetworkDefaultGateway' (returns SOAP_OK or error code)
        virtual int SetNetworkDefaultGateway(_ns1__SetNetworkDefaultGateway *ns1__SetNetworkDefaultGateway, _ns1__SetNetworkDefaultGatewayResponse &ns1__SetNetworkDefaultGatewayResponse)
        { return this->SetNetworkDefaultGateway(NULL, NULL, ns1__SetNetworkDefaultGateway, ns1__SetNetworkDefaultGatewayResponse); }
        virtual int SetNetworkDefaultGateway(const char *soap_endpoint, const char *soap_action, _ns1__SetNetworkDefaultGateway *ns1__SetNetworkDefaultGateway, _ns1__SetNetworkDefaultGatewayResponse &ns1__SetNetworkDefaultGatewayResponse);
        /// Web service operation 'GetZeroConfiguration' (returns SOAP_OK or error code)
        virtual int GetZeroConfiguration(_ns1__GetZeroConfiguration *ns1__GetZeroConfiguration, _ns1__GetZeroConfigurationResponse &ns1__GetZeroConfigurationResponse)
        { return this->GetZeroConfiguration(NULL, NULL, ns1__GetZeroConfiguration, ns1__GetZeroConfigurationResponse); }
        virtual int GetZeroConfiguration(const char *soap_endpoint, const char *soap_action, _ns1__GetZeroConfiguration *ns1__GetZeroConfiguration, _ns1__GetZeroConfigurationResponse &ns1__GetZeroConfigurationResponse);
        /// Web service operation 'SetZeroConfiguration' (returns SOAP_OK or error code)
        virtual int SetZeroConfiguration(_ns1__SetZeroConfiguration *ns1__SetZeroConfiguration, _ns1__SetZeroConfigurationResponse &ns1__SetZeroConfigurationResponse)
        { return this->SetZeroConfiguration(NULL, NULL, ns1__SetZeroConfiguration, ns1__SetZeroConfigurationResponse); }
        virtual int SetZeroConfiguration(const char *soap_endpoint, const char *soap_action, _ns1__SetZeroConfiguration *ns1__SetZeroConfiguration, _ns1__SetZeroConfigurationResponse &ns1__SetZeroConfigurationResponse);
        /// Web service operation 'GetIPAddressFilter' (returns SOAP_OK or error code)
        virtual int GetIPAddressFilter(_ns1__GetIPAddressFilter *ns1__GetIPAddressFilter, _ns1__GetIPAddressFilterResponse &ns1__GetIPAddressFilterResponse)
        { return this->GetIPAddressFilter(NULL, NULL, ns1__GetIPAddressFilter, ns1__GetIPAddressFilterResponse); }
        virtual int GetIPAddressFilter(const char *soap_endpoint, const char *soap_action, _ns1__GetIPAddressFilter *ns1__GetIPAddressFilter, _ns1__GetIPAddressFilterResponse &ns1__GetIPAddressFilterResponse);
        /// Web service operation 'SetIPAddressFilter' (returns SOAP_OK or error code)
        virtual int SetIPAddressFilter(_ns1__SetIPAddressFilter *ns1__SetIPAddressFilter, _ns1__SetIPAddressFilterResponse &ns1__SetIPAddressFilterResponse)
        { return this->SetIPAddressFilter(NULL, NULL, ns1__SetIPAddressFilter, ns1__SetIPAddressFilterResponse); }
        virtual int SetIPAddressFilter(const char *soap_endpoint, const char *soap_action, _ns1__SetIPAddressFilter *ns1__SetIPAddressFilter, _ns1__SetIPAddressFilterResponse &ns1__SetIPAddressFilterResponse);
        /// Web service operation 'AddIPAddressFilter' (returns SOAP_OK or error code)
        virtual int AddIPAddressFilter(_ns1__AddIPAddressFilter *ns1__AddIPAddressFilter, _ns1__AddIPAddressFilterResponse &ns1__AddIPAddressFilterResponse)
        { return this->AddIPAddressFilter(NULL, NULL, ns1__AddIPAddressFilter, ns1__AddIPAddressFilterResponse); }
        virtual int AddIPAddressFilter(const char *soap_endpoint, const char *soap_action, _ns1__AddIPAddressFilter *ns1__AddIPAddressFilter, _ns1__AddIPAddressFilterResponse &ns1__AddIPAddressFilterResponse);
        /// Web service operation 'RemoveIPAddressFilter' (returns SOAP_OK or error code)
        virtual int RemoveIPAddressFilter(_ns1__RemoveIPAddressFilter *ns1__RemoveIPAddressFilter, _ns1__RemoveIPAddressFilterResponse &ns1__RemoveIPAddressFilterResponse)
        { return this->RemoveIPAddressFilter(NULL, NULL, ns1__RemoveIPAddressFilter, ns1__RemoveIPAddressFilterResponse); }
        virtual int RemoveIPAddressFilter(const char *soap_endpoint, const char *soap_action, _ns1__RemoveIPAddressFilter *ns1__RemoveIPAddressFilter, _ns1__RemoveIPAddressFilterResponse &ns1__RemoveIPAddressFilterResponse);
        /// Web service operation 'GetAccessPolicy' (returns SOAP_OK or error code)
        virtual int GetAccessPolicy(_ns1__GetAccessPolicy *ns1__GetAccessPolicy, _ns1__GetAccessPolicyResponse &ns1__GetAccessPolicyResponse)
        { return this->GetAccessPolicy(NULL, NULL, ns1__GetAccessPolicy, ns1__GetAccessPolicyResponse); }
        virtual int GetAccessPolicy(const char *soap_endpoint, const char *soap_action, _ns1__GetAccessPolicy *ns1__GetAccessPolicy, _ns1__GetAccessPolicyResponse &ns1__GetAccessPolicyResponse);
        /// Web service operation 'SetAccessPolicy' (returns SOAP_OK or error code)
        virtual int SetAccessPolicy(_ns1__SetAccessPolicy *ns1__SetAccessPolicy, _ns1__SetAccessPolicyResponse &ns1__SetAccessPolicyResponse)
        { return this->SetAccessPolicy(NULL, NULL, ns1__SetAccessPolicy, ns1__SetAccessPolicyResponse); }
        virtual int SetAccessPolicy(const char *soap_endpoint, const char *soap_action, _ns1__SetAccessPolicy *ns1__SetAccessPolicy, _ns1__SetAccessPolicyResponse &ns1__SetAccessPolicyResponse);
        /// Web service operation 'CreateCertificate' (returns SOAP_OK or error code)
        virtual int CreateCertificate(_ns1__CreateCertificate *ns1__CreateCertificate, _ns1__CreateCertificateResponse &ns1__CreateCertificateResponse)
        { return this->CreateCertificate(NULL, NULL, ns1__CreateCertificate, ns1__CreateCertificateResponse); }
        virtual int CreateCertificate(const char *soap_endpoint, const char *soap_action, _ns1__CreateCertificate *ns1__CreateCertificate, _ns1__CreateCertificateResponse &ns1__CreateCertificateResponse);
        /// Web service operation 'GetCertificates' (returns SOAP_OK or error code)
        virtual int GetCertificates(_ns1__GetCertificates *ns1__GetCertificates, _ns1__GetCertificatesResponse &ns1__GetCertificatesResponse)
        { return this->GetCertificates(NULL, NULL, ns1__GetCertificates, ns1__GetCertificatesResponse); }
        virtual int GetCertificates(const char *soap_endpoint, const char *soap_action, _ns1__GetCertificates *ns1__GetCertificates, _ns1__GetCertificatesResponse &ns1__GetCertificatesResponse);
        /// Web service operation 'GetCertificatesStatus' (returns SOAP_OK or error code)
        virtual int GetCertificatesStatus(_ns1__GetCertificatesStatus *ns1__GetCertificatesStatus, _ns1__GetCertificatesStatusResponse &ns1__GetCertificatesStatusResponse)
        { return this->GetCertificatesStatus(NULL, NULL, ns1__GetCertificatesStatus, ns1__GetCertificatesStatusResponse); }
        virtual int GetCertificatesStatus(const char *soap_endpoint, const char *soap_action, _ns1__GetCertificatesStatus *ns1__GetCertificatesStatus, _ns1__GetCertificatesStatusResponse &ns1__GetCertificatesStatusResponse);
        /// Web service operation 'SetCertificatesStatus' (returns SOAP_OK or error code)
        virtual int SetCertificatesStatus(_ns1__SetCertificatesStatus *ns1__SetCertificatesStatus, _ns1__SetCertificatesStatusResponse &ns1__SetCertificatesStatusResponse)
        { return this->SetCertificatesStatus(NULL, NULL, ns1__SetCertificatesStatus, ns1__SetCertificatesStatusResponse); }
        virtual int SetCertificatesStatus(const char *soap_endpoint, const char *soap_action, _ns1__SetCertificatesStatus *ns1__SetCertificatesStatus, _ns1__SetCertificatesStatusResponse &ns1__SetCertificatesStatusResponse);
        /// Web service operation 'DeleteCertificates' (returns SOAP_OK or error code)
        virtual int DeleteCertificates(_ns1__DeleteCertificates *ns1__DeleteCertificates, _ns1__DeleteCertificatesResponse &ns1__DeleteCertificatesResponse)
        { return this->DeleteCertificates(NULL, NULL, ns1__DeleteCertificates, ns1__DeleteCertificatesResponse); }
        virtual int DeleteCertificates(const char *soap_endpoint, const char *soap_action, _ns1__DeleteCertificates *ns1__DeleteCertificates, _ns1__DeleteCertificatesResponse &ns1__DeleteCertificatesResponse);
        /// Web service operation 'GetPkcs10Request' (returns SOAP_OK or error code)
        virtual int GetPkcs10Request(_ns1__GetPkcs10Request *ns1__GetPkcs10Request, _ns1__GetPkcs10RequestResponse &ns1__GetPkcs10RequestResponse)
        { return this->GetPkcs10Request(NULL, NULL, ns1__GetPkcs10Request, ns1__GetPkcs10RequestResponse); }
        virtual int GetPkcs10Request(const char *soap_endpoint, const char *soap_action, _ns1__GetPkcs10Request *ns1__GetPkcs10Request, _ns1__GetPkcs10RequestResponse &ns1__GetPkcs10RequestResponse);
        /// Web service operation 'LoadCertificates' (returns SOAP_OK or error code)
        virtual int LoadCertificates(_ns1__LoadCertificates *ns1__LoadCertificates, _ns1__LoadCertificatesResponse &ns1__LoadCertificatesResponse)
        { return this->LoadCertificates(NULL, NULL, ns1__LoadCertificates, ns1__LoadCertificatesResponse); }
        virtual int LoadCertificates(const char *soap_endpoint, const char *soap_action, _ns1__LoadCertificates *ns1__LoadCertificates, _ns1__LoadCertificatesResponse &ns1__LoadCertificatesResponse);
        /// Web service operation 'GetClientCertificateMode' (returns SOAP_OK or error code)
        virtual int GetClientCertificateMode(_ns1__GetClientCertificateMode *ns1__GetClientCertificateMode, _ns1__GetClientCertificateModeResponse &ns1__GetClientCertificateModeResponse)
        { return this->GetClientCertificateMode(NULL, NULL, ns1__GetClientCertificateMode, ns1__GetClientCertificateModeResponse); }
        virtual int GetClientCertificateMode(const char *soap_endpoint, const char *soap_action, _ns1__GetClientCertificateMode *ns1__GetClientCertificateMode, _ns1__GetClientCertificateModeResponse &ns1__GetClientCertificateModeResponse);
        /// Web service operation 'SetClientCertificateMode' (returns SOAP_OK or error code)
        virtual int SetClientCertificateMode(_ns1__SetClientCertificateMode *ns1__SetClientCertificateMode, _ns1__SetClientCertificateModeResponse &ns1__SetClientCertificateModeResponse)
        { return this->SetClientCertificateMode(NULL, NULL, ns1__SetClientCertificateMode, ns1__SetClientCertificateModeResponse); }
        virtual int SetClientCertificateMode(const char *soap_endpoint, const char *soap_action, _ns1__SetClientCertificateMode *ns1__SetClientCertificateMode, _ns1__SetClientCertificateModeResponse &ns1__SetClientCertificateModeResponse);
        /// Web service operation 'GetRelayOutputs' (returns SOAP_OK or error code)
        virtual int GetRelayOutputs(_ns1__GetRelayOutputs *ns1__GetRelayOutputs, _ns1__GetRelayOutputsResponse &ns1__GetRelayOutputsResponse)
        { return this->GetRelayOutputs(NULL, NULL, ns1__GetRelayOutputs, ns1__GetRelayOutputsResponse); }
        virtual int GetRelayOutputs(const char *soap_endpoint, const char *soap_action, _ns1__GetRelayOutputs *ns1__GetRelayOutputs, _ns1__GetRelayOutputsResponse &ns1__GetRelayOutputsResponse);
        /// Web service operation 'SetRelayOutputSettings' (returns SOAP_OK or error code)
        virtual int SetRelayOutputSettings(_ns1__SetRelayOutputSettings *ns1__SetRelayOutputSettings, _ns1__SetRelayOutputSettingsResponse &ns1__SetRelayOutputSettingsResponse)
        { return this->SetRelayOutputSettings(NULL, NULL, ns1__SetRelayOutputSettings, ns1__SetRelayOutputSettingsResponse); }
        virtual int SetRelayOutputSettings(const char *soap_endpoint, const char *soap_action, _ns1__SetRelayOutputSettings *ns1__SetRelayOutputSettings, _ns1__SetRelayOutputSettingsResponse &ns1__SetRelayOutputSettingsResponse);
        /// Web service operation 'SetRelayOutputState' (returns SOAP_OK or error code)
        virtual int SetRelayOutputState(_ns1__SetRelayOutputState *ns1__SetRelayOutputState, _ns1__SetRelayOutputStateResponse &ns1__SetRelayOutputStateResponse)
        { return this->SetRelayOutputState(NULL, NULL, ns1__SetRelayOutputState, ns1__SetRelayOutputStateResponse); }
        virtual int SetRelayOutputState(const char *soap_endpoint, const char *soap_action, _ns1__SetRelayOutputState *ns1__SetRelayOutputState, _ns1__SetRelayOutputStateResponse &ns1__SetRelayOutputStateResponse);
        /// Web service operation 'SendAuxiliaryCommand' (returns SOAP_OK or error code)
        virtual int SendAuxiliaryCommand(_ns1__SendAuxiliaryCommand *ns1__SendAuxiliaryCommand, _ns1__SendAuxiliaryCommandResponse &ns1__SendAuxiliaryCommandResponse)
        { return this->SendAuxiliaryCommand(NULL, NULL, ns1__SendAuxiliaryCommand, ns1__SendAuxiliaryCommandResponse); }
        virtual int SendAuxiliaryCommand(const char *soap_endpoint, const char *soap_action, _ns1__SendAuxiliaryCommand *ns1__SendAuxiliaryCommand, _ns1__SendAuxiliaryCommandResponse &ns1__SendAuxiliaryCommandResponse);
        /// Web service operation 'GetCACertificates' (returns SOAP_OK or error code)
        virtual int GetCACertificates(_ns1__GetCACertificates *ns1__GetCACertificates, _ns1__GetCACertificatesResponse &ns1__GetCACertificatesResponse)
        { return this->GetCACertificates(NULL, NULL, ns1__GetCACertificates, ns1__GetCACertificatesResponse); }
        virtual int GetCACertificates(const char *soap_endpoint, const char *soap_action, _ns1__GetCACertificates *ns1__GetCACertificates, _ns1__GetCACertificatesResponse &ns1__GetCACertificatesResponse);
        /// Web service operation 'LoadCertificateWithPrivateKey' (returns SOAP_OK or error code)
        virtual int LoadCertificateWithPrivateKey(_ns1__LoadCertificateWithPrivateKey *ns1__LoadCertificateWithPrivateKey, _ns1__LoadCertificateWithPrivateKeyResponse &ns1__LoadCertificateWithPrivateKeyResponse)
        { return this->LoadCertificateWithPrivateKey(NULL, NULL, ns1__LoadCertificateWithPrivateKey, ns1__LoadCertificateWithPrivateKeyResponse); }
        virtual int LoadCertificateWithPrivateKey(const char *soap_endpoint, const char *soap_action, _ns1__LoadCertificateWithPrivateKey *ns1__LoadCertificateWithPrivateKey, _ns1__LoadCertificateWithPrivateKeyResponse &ns1__LoadCertificateWithPrivateKeyResponse);
        /// Web service operation 'GetCertificateInformation' (returns SOAP_OK or error code)
        virtual int GetCertificateInformation(_ns1__GetCertificateInformation *ns1__GetCertificateInformation, _ns1__GetCertificateInformationResponse &ns1__GetCertificateInformationResponse)
        { return this->GetCertificateInformation(NULL, NULL, ns1__GetCertificateInformation, ns1__GetCertificateInformationResponse); }
        virtual int GetCertificateInformation(const char *soap_endpoint, const char *soap_action, _ns1__GetCertificateInformation *ns1__GetCertificateInformation, _ns1__GetCertificateInformationResponse &ns1__GetCertificateInformationResponse);
        /// Web service operation 'LoadCACertificates' (returns SOAP_OK or error code)
        virtual int LoadCACertificates(_ns1__LoadCACertificates *ns1__LoadCACertificates, _ns1__LoadCACertificatesResponse &ns1__LoadCACertificatesResponse)
        { return this->LoadCACertificates(NULL, NULL, ns1__LoadCACertificates, ns1__LoadCACertificatesResponse); }
        virtual int LoadCACertificates(const char *soap_endpoint, const char *soap_action, _ns1__LoadCACertificates *ns1__LoadCACertificates, _ns1__LoadCACertificatesResponse &ns1__LoadCACertificatesResponse);
        /// Web service operation 'CreateDot1XConfiguration' (returns SOAP_OK or error code)
        virtual int CreateDot1XConfiguration(_ns1__CreateDot1XConfiguration *ns1__CreateDot1XConfiguration, _ns1__CreateDot1XConfigurationResponse &ns1__CreateDot1XConfigurationResponse)
        { return this->CreateDot1XConfiguration(NULL, NULL, ns1__CreateDot1XConfiguration, ns1__CreateDot1XConfigurationResponse); }
        virtual int CreateDot1XConfiguration(const char *soap_endpoint, const char *soap_action, _ns1__CreateDot1XConfiguration *ns1__CreateDot1XConfiguration, _ns1__CreateDot1XConfigurationResponse &ns1__CreateDot1XConfigurationResponse);
        /// Web service operation 'SetDot1XConfiguration' (returns SOAP_OK or error code)
        virtual int SetDot1XConfiguration(_ns1__SetDot1XConfiguration *ns1__SetDot1XConfiguration, _ns1__SetDot1XConfigurationResponse &ns1__SetDot1XConfigurationResponse)
        { return this->SetDot1XConfiguration(NULL, NULL, ns1__SetDot1XConfiguration, ns1__SetDot1XConfigurationResponse); }
        virtual int SetDot1XConfiguration(const char *soap_endpoint, const char *soap_action, _ns1__SetDot1XConfiguration *ns1__SetDot1XConfiguration, _ns1__SetDot1XConfigurationResponse &ns1__SetDot1XConfigurationResponse);
        /// Web service operation 'GetDot1XConfiguration' (returns SOAP_OK or error code)
        virtual int GetDot1XConfiguration(_ns1__GetDot1XConfiguration *ns1__GetDot1XConfiguration, _ns1__GetDot1XConfigurationResponse &ns1__GetDot1XConfigurationResponse)
        { return this->GetDot1XConfiguration(NULL, NULL, ns1__GetDot1XConfiguration, ns1__GetDot1XConfigurationResponse); }
        virtual int GetDot1XConfiguration(const char *soap_endpoint, const char *soap_action, _ns1__GetDot1XConfiguration *ns1__GetDot1XConfiguration, _ns1__GetDot1XConfigurationResponse &ns1__GetDot1XConfigurationResponse);
        /// Web service operation 'GetDot1XConfigurations' (returns SOAP_OK or error code)
        virtual int GetDot1XConfigurations(_ns1__GetDot1XConfigurations *ns1__GetDot1XConfigurations, _ns1__GetDot1XConfigurationsResponse &ns1__GetDot1XConfigurationsResponse)
        { return this->GetDot1XConfigurations(NULL, NULL, ns1__GetDot1XConfigurations, ns1__GetDot1XConfigurationsResponse); }
        virtual int GetDot1XConfigurations(const char *soap_endpoint, const char *soap_action, _ns1__GetDot1XConfigurations *ns1__GetDot1XConfigurations, _ns1__GetDot1XConfigurationsResponse &ns1__GetDot1XConfigurationsResponse);
        /// Web service operation 'DeleteDot1XConfiguration' (returns SOAP_OK or error code)
        virtual int DeleteDot1XConfiguration(_ns1__DeleteDot1XConfiguration *ns1__DeleteDot1XConfiguration, _ns1__DeleteDot1XConfigurationResponse &ns1__DeleteDot1XConfigurationResponse)
        { return this->DeleteDot1XConfiguration(NULL, NULL, ns1__DeleteDot1XConfiguration, ns1__DeleteDot1XConfigurationResponse); }
        virtual int DeleteDot1XConfiguration(const char *soap_endpoint, const char *soap_action, _ns1__DeleteDot1XConfiguration *ns1__DeleteDot1XConfiguration, _ns1__DeleteDot1XConfigurationResponse &ns1__DeleteDot1XConfigurationResponse);
        /// Web service operation 'GetDot11Capabilities' (returns SOAP_OK or error code)
        virtual int GetDot11Capabilities(_ns1__GetDot11Capabilities *ns1__GetDot11Capabilities, _ns1__GetDot11CapabilitiesResponse &ns1__GetDot11CapabilitiesResponse)
        { return this->GetDot11Capabilities(NULL, NULL, ns1__GetDot11Capabilities, ns1__GetDot11CapabilitiesResponse); }
        virtual int GetDot11Capabilities(const char *soap_endpoint, const char *soap_action, _ns1__GetDot11Capabilities *ns1__GetDot11Capabilities, _ns1__GetDot11CapabilitiesResponse &ns1__GetDot11CapabilitiesResponse);
        /// Web service operation 'GetDot11Status' (returns SOAP_OK or error code)
        virtual int GetDot11Status(_ns1__GetDot11Status *ns1__GetDot11Status, _ns1__GetDot11StatusResponse &ns1__GetDot11StatusResponse)
        { return this->GetDot11Status(NULL, NULL, ns1__GetDot11Status, ns1__GetDot11StatusResponse); }
        virtual int GetDot11Status(const char *soap_endpoint, const char *soap_action, _ns1__GetDot11Status *ns1__GetDot11Status, _ns1__GetDot11StatusResponse &ns1__GetDot11StatusResponse);
        /// Web service operation 'ScanAvailableDot11Networks' (returns SOAP_OK or error code)
        virtual int ScanAvailableDot11Networks(_ns1__ScanAvailableDot11Networks *ns1__ScanAvailableDot11Networks, _ns1__ScanAvailableDot11NetworksResponse &ns1__ScanAvailableDot11NetworksResponse)
        { return this->ScanAvailableDot11Networks(NULL, NULL, ns1__ScanAvailableDot11Networks, ns1__ScanAvailableDot11NetworksResponse); }
        virtual int ScanAvailableDot11Networks(const char *soap_endpoint, const char *soap_action, _ns1__ScanAvailableDot11Networks *ns1__ScanAvailableDot11Networks, _ns1__ScanAvailableDot11NetworksResponse &ns1__ScanAvailableDot11NetworksResponse);
        /// Web service operation 'GetSystemUris' (returns SOAP_OK or error code)
        virtual int GetSystemUris(_ns1__GetSystemUris *ns1__GetSystemUris, _ns1__GetSystemUrisResponse &ns1__GetSystemUrisResponse)
        { return this->GetSystemUris(NULL, NULL, ns1__GetSystemUris, ns1__GetSystemUrisResponse); }
        virtual int GetSystemUris(const char *soap_endpoint, const char *soap_action, _ns1__GetSystemUris *ns1__GetSystemUris, _ns1__GetSystemUrisResponse &ns1__GetSystemUrisResponse);
        /// Web service operation 'StartFirmwareUpgrade' (returns SOAP_OK or error code)
        virtual int StartFirmwareUpgrade(_ns1__StartFirmwareUpgrade *ns1__StartFirmwareUpgrade, _ns1__StartFirmwareUpgradeResponse &ns1__StartFirmwareUpgradeResponse)
        { return this->StartFirmwareUpgrade(NULL, NULL, ns1__StartFirmwareUpgrade, ns1__StartFirmwareUpgradeResponse); }
        virtual int StartFirmwareUpgrade(const char *soap_endpoint, const char *soap_action, _ns1__StartFirmwareUpgrade *ns1__StartFirmwareUpgrade, _ns1__StartFirmwareUpgradeResponse &ns1__StartFirmwareUpgradeResponse);
        /// Web service operation 'StartSystemRestore' (returns SOAP_OK or error code)
        virtual int StartSystemRestore(_ns1__StartSystemRestore *ns1__StartSystemRestore, _ns1__StartSystemRestoreResponse &ns1__StartSystemRestoreResponse)
        { return this->StartSystemRestore(NULL, NULL, ns1__StartSystemRestore, ns1__StartSystemRestoreResponse); }
        virtual int StartSystemRestore(const char *soap_endpoint, const char *soap_action, _ns1__StartSystemRestore *ns1__StartSystemRestore, _ns1__StartSystemRestoreResponse &ns1__StartSystemRestoreResponse);
        /// Web service operation 'GetStorageConfigurations' (returns SOAP_OK or error code)
        virtual int GetStorageConfigurations(_ns1__GetStorageConfigurations *ns1__GetStorageConfigurations, _ns1__GetStorageConfigurationsResponse &ns1__GetStorageConfigurationsResponse)
        { return this->GetStorageConfigurations(NULL, NULL, ns1__GetStorageConfigurations, ns1__GetStorageConfigurationsResponse); }
        virtual int GetStorageConfigurations(const char *soap_endpoint, const char *soap_action, _ns1__GetStorageConfigurations *ns1__GetStorageConfigurations, _ns1__GetStorageConfigurationsResponse &ns1__GetStorageConfigurationsResponse);
        /// Web service operation 'CreateStorageConfiguration' (returns SOAP_OK or error code)
        virtual int CreateStorageConfiguration(_ns1__CreateStorageConfiguration *ns1__CreateStorageConfiguration, _ns1__CreateStorageConfigurationResponse &ns1__CreateStorageConfigurationResponse)
        { return this->CreateStorageConfiguration(NULL, NULL, ns1__CreateStorageConfiguration, ns1__CreateStorageConfigurationResponse); }
        virtual int CreateStorageConfiguration(const char *soap_endpoint, const char *soap_action, _ns1__CreateStorageConfiguration *ns1__CreateStorageConfiguration, _ns1__CreateStorageConfigurationResponse &ns1__CreateStorageConfigurationResponse);
        /// Web service operation 'GetStorageConfiguration' (returns SOAP_OK or error code)
        virtual int GetStorageConfiguration(_ns1__GetStorageConfiguration *ns1__GetStorageConfiguration, _ns1__GetStorageConfigurationResponse &ns1__GetStorageConfigurationResponse)
        { return this->GetStorageConfiguration(NULL, NULL, ns1__GetStorageConfiguration, ns1__GetStorageConfigurationResponse); }
        virtual int GetStorageConfiguration(const char *soap_endpoint, const char *soap_action, _ns1__GetStorageConfiguration *ns1__GetStorageConfiguration, _ns1__GetStorageConfigurationResponse &ns1__GetStorageConfigurationResponse);
        /// Web service operation 'SetStorageConfiguration' (returns SOAP_OK or error code)
        virtual int SetStorageConfiguration(_ns1__SetStorageConfiguration *ns1__SetStorageConfiguration, _ns1__SetStorageConfigurationResponse &ns1__SetStorageConfigurationResponse)
        { return this->SetStorageConfiguration(NULL, NULL, ns1__SetStorageConfiguration, ns1__SetStorageConfigurationResponse); }
        virtual int SetStorageConfiguration(const char *soap_endpoint, const char *soap_action, _ns1__SetStorageConfiguration *ns1__SetStorageConfiguration, _ns1__SetStorageConfigurationResponse &ns1__SetStorageConfigurationResponse);
        /// Web service operation 'DeleteStorageConfiguration' (returns SOAP_OK or error code)
        virtual int DeleteStorageConfiguration(_ns1__DeleteStorageConfiguration *ns1__DeleteStorageConfiguration, _ns1__DeleteStorageConfigurationResponse &ns1__DeleteStorageConfigurationResponse)
        { return this->DeleteStorageConfiguration(NULL, NULL, ns1__DeleteStorageConfiguration, ns1__DeleteStorageConfigurationResponse); }
        virtual int DeleteStorageConfiguration(const char *soap_endpoint, const char *soap_action, _ns1__DeleteStorageConfiguration *ns1__DeleteStorageConfiguration, _ns1__DeleteStorageConfigurationResponse &ns1__DeleteStorageConfigurationResponse);
    };
#endif
